### ISSUE TITLE
No contentEncoding option for attachments?

### ISSUE THREAD

**Issue by davisford** [andris9/Nodemailer#356]
Is it not possible to specify the content encoding for an attachment?  I tried the `encoding` property, but that seems to work only if the actual content is a string.

I'm trying to attach a pdf stored on S3, but the content-encoding is `gzip`, and I can successfully send it ok, but it won't open in any mail app, b/c it is actually still gzip'd.

If it currently isn't possible to specify this, would you accept a PR that adds this support (assuming it is feasible)?

**Comment by andris9** [comment]
It's been a while but this issue is now resolved in v1.7.0 where needle is used instead of hyperquest.

**Comment by davisford** [comment]
thank you sir!
