### ISSUE TITLE
Not working with my own mail service

### ISSUE THREAD

**Issue by pekpon** [andris9/Nodemailer#358]
Hello!

I can't use nodemailer with my own mail service. I'm trying to send mails with the SMTP transport but every time is crashing.

Errors:
```
[Error: 140735268836112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:787:]
```
```
[Error: DEPTH_ZERO_SELF_SIGNED_CERT]
```

I'm filling port, host, secure: true, auth credentials...everything is correct but crashes.
I'm testing now with https://github.com/eleith/emailjs and it look like that this really works with the same configuration.

Hope that helps, thanks!

**Comment by dhenriques** [comment]
I've got a a similar problem, tried already the secure=false and requireTLS=true, and it says that the email was sent but actualy wasn't.

And jinjojohnson solution is from a older version from nodemailer, not sure if is a good option, but tried and get "Email message sent: undefined", also the mail was not really sent :/

**Comment by drlogout** [comment]
Same error here.

**Comment by niknah** [comment]
I'm using v1.

This works...
smtpTransport({ignoreTLS:true,secure:false});

If the default option for smtpTransport is localhost:25 then a secure connection should probably be turned off too.

The default blank smtpTransport({}) settings will try to connect to localhost:25 using a secure connection.  It won't work on most newly installed systems cause they don't have a proper signed certificate.

**Comment by andris9** [comment]
In case of TLS errors you can use the `tls` option when setting up the transport. It is an object that takes passes its values to [tls.connect](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback). 

So if you get DEPTH_ZERO_SELF_SIGNED_CERT error, use

```
tls: {
    rejectUnauthorized: false
}
```

If you get protocol errors, change the protocol, for example for SSLv3 use this

```
tls: {
    secureProtocol: 'SSLv3_method'
}
```

Boths SSLv2 and SSLv3 are disabled by default in node, so if your server explicitly wants to use it, you have to enable it. See details [here](https://nodejs.org/api/tls.html#tls_protocol_support)
