### ISSUE TITLE
Attachment does not support Chinese file name?

### ISSUE THREAD

**Issue by hanan198501** [andris9/Nodemailer#374]
when i send Attachment like this:

var mailOptions = {
    ...
    attachments: [
    { filename: '韩安.jpg',
        path: '/Users/hanan/project/ksend/韩安.jpg' },
    { filename: 'README哈哈.md',
        path: '/Users/hanan/project/ksend/README哈哈.md' }
]
    ...
}

Can successfully sent。

but， in the receiving mailbox, the file name into like ：
tcmime.1388.1527.1742.bin 
tcmime.2438.2598.2671.bin

How can I solve this problem？ thank you。

**Comment by andris9** [comment]
This is probably an issue on the receiving side. Nodemailer correctly encodes the filename, for example the headers for 韩安.jpg should look like this:

```
Content-Type: image/jpeg
Content-Disposition: attachment; filename*0*=utf-8''%E9%9F%A9%E5%AE%89.jpg
Content-Transfer-Encoding: base64
```

Nodemailer does note generate filenames like 'tcmime.*' , so this must have been set in transit. Additionally, Nodemailer uses correct Content-Type, so the attachment should not be '.bin' but '.jpg'.

Anyway, based on that description, I bwould say, it is not an issue with Nodemailer but with the receiver.

**Comment by sherry718** [comment]
发送给qq邮箱就是这种情况，但是现在大部分用户都是用qq邮箱的，怎么解决呢？

**Comment by andris9** [comment]
Latest version of Nodemailer is QQ compatible

**Comment by sherry718** [comment]
Thanks，and it‘s work

**Comment by liangmark** [comment]
The filename of attachment is only allowed four Chinese characters?
For example:
my filename is "非全日制劳动合同.pdf", but in the receiving mailbox, the file name into like ：
![snip20171208_8](https://user-images.githubusercontent.com/12019458/33755374-60d08a80-dc2b-11e7-8967-d64f4566bc52.png)

**Comment by liangmark** [comment]
@andris9 How can I solve this problem？ thank you。

**Comment by andris9** [comment]
@liangmark you would need to do the following in order to debug:

1. send the same attachment from another mailer. Use the same SMTP account you are using with Nodemailer
2. verify that the received mail has proper filename for the attachment
3. download the sources (RFC822 formatted, usually an eml file or "show original" or "show message source" etc.) of both messages (1 of the correct message and 1 sent from Nodemailer) and  send these to me

**Comment by liangmark** [comment]
@andris9 I change then mailer, the results below:
the mail by Nodemailer:
![snip20171211_16](https://user-images.githubusercontent.com/12019458/33821651-944ff7fe-de8f-11e7-9741-17693ebc8aff.png)
the other mailer:
![snip20171211_17](https://user-images.githubusercontent.com/12019458/33821664-a2b332de-de8f-11e7-85ac-9992e972449a.png)

**Comment by andris9** [comment]
@lingmark can you give me the raw sources of these both emails? you would need to download these somehow from your email server as eml files and send these to me: andris.reinman@gmail.com
Without sources there is no way I can tell what is wrong with the message.

**Comment by liangmark** [comment]
I don't understand the third step，Can you explain to me? thank you very much!

**Comment by andris9** [comment]
@liangmark this usually depends on your provider. You need to get the email file stored on server. For reference in Gmail you can download the file like this: https://cloudup.com/cAp5SdmitYR

**Comment by liangmark** [comment]
I think I find the reason，I open the eml file by other email client, the attachment is OK. so it’s a mistake of my email client.Thank you very much!
