### ISSUE TITLE
possible to choose transfer encoding base64 in headers?

### ISSUE THREAD

**Issue by loveencounterflow** [andris9/Nodemailer#378]
i understand that UTF-8 is always used in headers; however, is there a way to choose `base64` over `quoted-printable` as the transfer encoding?

**Comment by andris9** [comment]
If you want to use base64 as the default encoding, you can add encoding: 'base64' in your mail options. See [message field docs](https://github.com/andris9/Nodemailer#e-mail-message-fields) for details

**Comment by loveencounterflow** [comment]
ah, i see. i did `transporter.sendMail({ 'encoding': 'base64', ... )}` and works as advertised. thx!
