### ISSUE TITLE
Send mail with mongolia language is not working.

### ISSUE THREAD

**Issue by nguyenquynhan** [andris9/Nodemailer#379]
Hi all member of nodemailer!
I send mail with mongolia language is not working. I don't receive email though reponse is OK.
- send mail input:
{
	"from" : "nguyenquynhan18@gmail.com",
	"to":           ["nguyenquynhan18@gmail.com"],
	"subject":      "Refer from your friend - nguyenquynhan18@gmail.com",
	"text":  "Simple email test",
	"html":  "Credit App танилцуулж байна</div>\n\t\t\t\t<span style=''>\n\t\t\t\t\tCredit App таны хүрээний хүмүүсийн зорилго хэрэгцээнд тусгайлан зориулан хийсэн. Таны ойр орчмын дэлгүүрийн тусгай урамшуулал, хүргэлтийн үйлчилгээ, үйл явдлын мэдээлэл, холбоо харилцаа болон бусад зүйлсийг танд санал болгож байна"
}

- send mail reponse:
{ 
	accepted: [ 'nguyenquynhan18@gmail.com' ],
	  rejected: [],
	  response: '250 OK id=1YEvY9-00065e-Ix',
	  envelope:
		{ 
			from: 'noreply-deliva@nrh-group.com',
			to: [ 'nguyenquynhan18@gmail.com' ] 
		},
	  messageId: '1422086068814-e00ef409-bfb162fb-8f90664d@nrh-group.com' 
 }

------------------------------------------------------------------------------------------------------
- but I change body as below that OK, always receive email.
{
	"from" : "nguyenquynhan18@gmail.com",
	"to":           ["nguyenquynhan18@gmail.com"],
	"subject":      "Refer from your friend - nguyenquynhan18@gmail.com",
	"text":  "Simple email test",
	"html":  "Credit App танилцуулж байна"
}

- I use nodemailer 1.3.0, run on linux. Please help me resolve this problem.
Thanks you for yuor help.

**Comment by nguyenquynhan** [comment]
Oh just no problem of nodemailer, mail server receive mail below:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  nguyenquynhan18@gmail.com
    SMTP error from remote mail server after end of data:
    host outbound.mailspamprotection.com [184.154.58.226]:
    550 High probability of spam

------ This is a copy of the message, including all the headers. ------

Return-path: <noreply-deliva@nrh-group.com>
Received: from [113.161.86.164] (port=25088 helo=localhost.localdomain)
	by serv01.siteground133.com with esmtpsa (UNKNOWN:RC4-SHA:128)
	(Exim 4.80.1)
	(envelope-from <noreply-deliva@nrh-group.com>)
	id 1YFbAX-0002oL-Pn
	for nguyenquynhan18@gmail.com; Sun, 25 Jan 2015 22:20:58 -0600
X-Mailer: Nodemailer (0.7.1; +http://github.com/andris9/nodemailer;
 smtp/0.3.34)
Date: Mon, 26 Jan 2015 04:20:49 GMT
Message-Id: <376e6f15716f5f627db8f9b9745cd2@localhost.localdomain>
From: noreply-deliva@nrh-group.com
To: nguyenquynhan18@gmail.com
Subject: Refer from your friend - nguyenquynhan18@gmail.com
Content-Type: multipart/alternative;
 boundary="----Nodemailer-0.7.1-?=_1-1422246052921"
MIME-Version: 1.0

------Nodemailer-0.7.1-?=_1-1422246052921
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

**Comment by andris9** [comment]
There's nothing wrong with Nodemailer, the message is sent out fine. For example this is what I see in my email client using the same email options after receiving the message:

![](https://cldup.com/Ff7-oo7wqD.png)

There is something probably going on with the parser or somewhere else.

**Comment by nguyenquynhan** [comment]
Yes, there's nothing wrong with Nodemailer, problem with my mail server.
Thanks andris!
