### ISSUE TITLE
Empty attachment not attached

### ISSUE THREAD

**Issue by ilanbiala** [andris9/Nodemailer#380]
I have an empty attachment, that isn't being attached. I'm using this code:
```
options = {
    to: 'jdoe@abc.org',
    subject: 'CSV',
    text: 'Attached is the CSV.',
    html: 'Attached is the CSV.',
    attachments: [{
      filename: today.getDate() + '/' + (today.getMonth() + 1) +
        '/' + today.getFullYear() + '.csv',
      content: csv
    }]
  }
```
`csv` is an empty string, so shouldn't the attachment be an empty CSV file?

**Comment by andris9** [comment]
Are you using the latest version of Nodemailer? If I test such scenario, the empty csv file is attached

Attachment declaration:

```
{
    filename: 'test.csv',
    content: ''
}
```

Generated raw message source:

```
------sinikael-?=_1-14223932817430.9231957795564085
Content-Type: text/csv
Content-Disposition: attachment; filename=test.csv


------sinikael-?=_1-14223932817430.9231957795564085--
```

**Comment by ilanbiala** [comment]
@andris9 even when I have this code, I don't get an attachment..what could be wrong?
```js
var csv = 'Breaded Chicken Sandwich,,1';
var today = new Date();

var options = {
    to: 'jdoe@abc.org',
    subject: 'JDoe',
    text: 'Attached is the CSV.',
    html: 'Attached is the CSV.',
    attachments: [{
      filename: 'JDoe-' + today.getDate() + '/' + (today.getMonth() + 1) +
        '/' + today.getFullYear() + '.csv',
      content: csv
    }]
  };
```

**Comment by ilanbiala** [comment]
@andris9 any ideas on why it doesn't work even when the file has content?? Does it have to do with the `/` character that doesn't work on windows?

**Comment by andris9** [comment]
I see nothing wrong with this code.

This is what the raw email looks like (everything ok):

```
------sinikael-?=_1-14227775893800.09766620001755655
Content-Type: text/csv
Content-Disposition: attachment; filename*0*=utf-8''JDoe-1%2F2%2F2015.csv
Content-Transfer-Encoding: 7bit

Breaded Chicken Sandwich,,1
------sinikael-?=_1-14227775893800.09766620001755655--
```

And this is what I see if I try to open the attachment:

![](https://cldup.com/DvZhvrr9SK.png)

**Comment by ilanbiala** [comment]
@andris9 ok I'll take another look at my code. Could it have to do with my transport (Mandrill)?

**Comment by andris9** [comment]
Might be related with the relay. Besides using slashes in filename is not a great idea either as the client needs to convert these to something else before saving the file to disk.

**Comment by ilanbiala** [comment]
Just changed to dashes. What is the relay?

**Comment by andris9** [comment]
Relay is the service that you are using to deliver the email. In your case that would be Mandrill. Some relays deliver emails as these are, with no modifications. Some do heavy modifications.
