### ISSUE TITLE
I can't install nodemailer

### ISSUE THREAD

**Issue by simonchan2013** [andris9/Nodemailer#381]
when i install nodemailer with the command ： npm install nodemailer
it return the error message blew：
npm ERR! 404 404 Not Found: nodemailer
npm ERR! 404
npm ERR! 404 'nodemailer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodemailer"
npm ERR! cwd E:\work\workspace_js\nodejs_test
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\work\workspace_js\nodejs_test\npm-debug.log
npm ERR! not ok code 0

**Comment by andris9** [comment]
Can't confirm, it might be an issue with your npm. When I try to run the same command, it succeeds:

```
npm install nodemailer
nodemailer@1.3.0 node_modules/nodemailer
├── hyperquest@0.3.0 (duplexer@0.1.1, through@2.2.7)
├── nodemailer-smtp-transport@0.1.13 (nodemailer-wellknown@0.1.4, smtp-connection@1.1.0)
├── buildmail@1.2.0 (libbase64@0.1.0, libqp@0.1.1, addressparser@0.3.2)
├── nodemailer-direct-transport@1.0.0 (smtp-connection@0.1.7)
└── libmime@0.1.7 (libbase64@0.1.0, libqp@0.1.1, iconv-lite@0.4.6)
```
