### ISSUE TITLE
Error: No recipients defined] code: 'EENVELOPE'

### ISSUE THREAD

**Issue by gahula** [andris9/Nodemailer#382]
Error: No recipients defined] code: 'EENVELOPE'

var SMTP = nodemailer.createTransport(smtpTransport({
    host: 'smtp.xxxx.xxx',
    port: '25', // Secure SSL (465) Secure TLS (587)
    secureConnection: false,
    name: 'Notifications',
    ignoreTLS: false,
    auth: {
        user: config.AuthConfig.nodemailer.username,
        pass: config.AuthConfig.nodemailer.password
    }
}));

**Comment by andris9** [comment]
`EENVELOPE` happens when you do not have any valid `to`, `cc` or `bcc` addresses defined.

**Comment by crxstxxn2305** [comment]
How can I get the code of the Exception?

**Comment by crxstxxn2305** [comment]
I know that the code is "EENVELOPE" but I need a numeric code to capture the Exception.
