### ISSUE TITLE
Send email without "to"

### ISSUE THREAD

**Issue by ndaidong** [andris9/Nodemailer#385]
Hi there,

I'm using Nodemailer 1.3.0 to send email as below:
```
function delivery(recipients, subject, content){
    var mail = {
        from: 'FOMO <news@fomo.link>',
        to: [],
        bcc: recipients,
        subject: subject,
        text: stripTags(content),
        html: content
    }

    Transporter.sendMail(mail);
}
```
The parameter *recipients* is a collection of several users. Because I would like to hide these email addresses from each user to another so I just pass them into "bcc" instead of "to". The emails were sent successfully but no receiver name appears:

![Email sent but no receiver name](http://i.imgur.com/Pu946dd.png) 

Is this an issue?

My environment: 

* Linux 64 bit
* Node.js 0.10.35
* npm 1.4.28
* nodemailer-smtp-transport  0.1.13

Thanks,
Dong Nguyen

**Comment by andris9** [comment]
Thats how bcc works – the recipient field is hidden and never shown. If you want to show the `to:` value, do not use *bcc* to send messages but send the message with a loop, where every recipient gets the message by their own name by using *to*.

So instead of 

```
sendMail({bcc: addressArray})
```

do this

```
addressArray.forEach(function(address){
    sendMail({to: address})
})
```

**Comment by ndaidong** [comment]
@andris9 : thank you for your suggestion.  

Using a loop to delivery one by one seems to the best solution here. I will apply this way.

**Comment by Sasicumaar** [comment]
Hi All,Is there any update on this for sending emails to multiple without using loop.

**Comment by andris9** [comment]
You do need to use loops. If you have a large number of emails to send then you probably should consider a queue system where you push all the meails to be sent to the queue on one end and then on the other end you have some worker processes that pull messages from the queue and send these out. See an AMQP based example [here](https://github.com/nodemailer/nodemailer-amqp-example)

**Comment by cajber** [comment]
What would qualify as a large number of emails? I'm creating a service that is sending transactional emails upwards of 1000-2000 each go. I'm also using an SMTP relay to send via (mailjet).
