### ISSUE TITLE
how to set bounce address

### ISSUE THREAD

**Issue by simonchan2013** [andris9/Nodemailer#387]
hi, i want to make all the bounce mail to a specified email address! how can i set the bounce address!
is there anyone can help me? thanks

**Comment by andris9** [comment]
Bounce address is defined with the `from` address of the SMTP envelope. By default the envelope is composed automatically from the `from`, `to`, `cc` and `bcc` mail option fields but you can override it with the `envelope` option, see example [here](https://github.com/andris9/Nodemailer#smtp-envelope).

Bear in mind that if you define your own envelope, you also need to include all recipient addresses, not just the sender address as the defaults are not used in this case.

**Comment by simonchan2013** [comment]
i have tried this way, but the mail still return to my sender address, even through i set the from address of the SMTP envelope to be bounce+mwpsy-simon.chen=corp.globalmarket.com@corp.globalmarket.com
