### ISSUE TITLE
how to set bounce address

### ISSUE THREAD

**Issue by simonchan2013** [andris9/Nodemailer#388]
i sorry, i don't how to reopen then issue, so i make a new issue. and i have tried you idea, but it still does not work.

hi, i want to make all the bounce mail to a specified email address! how can i set the bounce address!
is there anyone can help me? thanks

i have tried this way, but the mail still return to my sender address, even through i set the from address of the SMTP envelope to be bounce+mwpsy-simon.chen=corp.globalmarket.com@corp.globalmarket.com

**Comment by andris9** [comment]
If you have set up the envelope correctly, then your MTA changes the return path address and there's nothing you can do about it. Send a message to your own address with your desired bounce address setting. Once the message is received, see the source of it and look for the `Return-Path` header. If it is changed from the envelope.from address to the from header of the message or to the authenticated user address, then the MTA has changed the address.
