### ISSUE TITLE
Ignoring my Content-Type header

### ISSUE THREAD

**Issue by KaptainKrayola** [andris9/Nodemailer#389]
I have to set a very specific Content-Type header for sending multipart/related messages and nodemailer seems to be ignoring that I have specified the Content-Type header and is using "text/plain; format=flowed" instead.

Can you give me some way to tell nodemailer not to append its own Content-Type header if I need to use my very specific one?

**Comment by KaptainKrayola** [comment]
I thought using an Alternative would work but it does not.

**Comment by jamesmayes** [comment]
Similarly, I expected the body content to be encoded as UTF-8 by default.  Instead, it is as you suggest "text/plain; format=flowed".  Google thinks that the messages I send to a text Gmail-based recipient are Italian.  Example body:


MIME-Version: 1.0

------sinikael-?=_1-14260152040620.13629642967134714
Content-Type: text/html; format=flowed
Content-Transfer-Encoding: 7bit

<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Title</title></head><body><h2>Header/h2><p></p><div 
class="line"><strong>Name:</strong> Value</div><div class="line"><strong>Hostname:</strong> fqdn.com</div><p></p></body></html>
------sinikael-?=_1-14260152040620.13629642967134714
Content-Type: application/zip
Content-Disposition: attachment; filename=20150310T142000-0500.zip
Content-Transfer-Encoding: base64

UEsDBBQACAgIAIByakYAAAAAAAAAAAAAAA ... snip ... gAAABsAAAAAAAAAAAAAAAAAAAAAAGZtYy1lbmJhc2Vt
b2JpbGUtZXJyb3JzLmxvZ1BLBQYAAAAAAQABAEkAAACrAAAAAAA=
------sinikael-?=_1-14260152040620.13629642967134714--

**Comment by andris9** [comment]
@KaptainKrayola could you specify your use case? Currently Nodemailer is a opinionated module which means that for text context it detects the used format and then sets appropriate encoding itself.

@jamesmayes I have no idea what you mean by the messages being in Italian, could you specify what you are doing and what is the outcome. Probably create another issue for it.

**Comment by KaptainKrayola** [comment]
Wouldn't it still make sense to allow a user to override no matter how opinionated the module may be?  My use case is pretty specific and I can't say too much about it but suffice it to say, I need to be able to specify that header.  I have commented out your code to override it in my implementation but I do think giving someone a way to override the module's opinion would be a simple and user-friendly thing to do.

**Comment by andris9** [comment]
Could you still describe what you would like to do? Do you use some custom arguments for the content-type value or what? Format=flowed is nothing more than a transport encoding mechanism, it doesn't alter the value – once the message is delivered and decoded you should get the same value that was initially sent out.

**Comment by KaptainKrayola** [comment]
Yeah, I need to override ""text/plain; format=flowed"" completely.  In my case I have to use "Content-Type": 'multipart/related; [ ... a bunch of other custom data ... ]

What's happening is that I pass in my own content header and while it is included in the header,  the "text/plain; format=flowed" is written first and then it's the one that's processed. 

What i'd like to see if if the content-type header is include specifically it overrides the "text/plain; format=flowed" one completely.  Otherwise they compete for which one gets accepted.

**Comment by jamesmayes** [comment]
@andris9 I recently migrated from 0.7 to the 1.3.2 (with all necessary transport changes) and all of a sudden Gmail presents me with a choice to translate the multi-part message from Italian!  Very strange.

Sure, I'll create another issue.

**Comment by andris9** [comment]
Multipart tree makes up the backbone of Nodemailer messages. Nodemailer is a high level mailer module which means that you can define the needed values like text and html body and attachments and not care about the actual rfc822 structure. Injecting arbitrary mime nodes to the structure does not seem something that is required from such a module. If you really need to mess around with the structure of the message I'd suggest you to use lower level [buildmail](https://github.com/andris9/buildmail) module.
