### ISSUE TITLE
Dynamic email content with Bcc

### ISSUE THREAD

**Issue by kitlee** [andris9/Nodemailer#390]
This plugin works great!

And I now want to send mass email to the users in my database by setting the `bcc` field as an array of email addresses .
I hope to dynamically set the email html content, (different content for different user)

For example:
"Dear, {username}, your reference number is {referenceNo}."

Besides other template rendering engine, can I achieve this by using Nodemailer?

**Comment by andris9** [comment]
You can't do this wiht BCC as you only send a single message wich is copied to all recipient. if you want personalized messages, you should send a single message to every recipient.

```javascript
var recipients = ['address1', 'address2', ...];

for(var i=0; i<recipients; i++){
    transport.sendMail({to: recipients[i], text: '...'})
}
```
