### ISSUE TITLE
X-Mailer

### ISSUE THREAD

**Issue by thenitai** [andris9/Nodemailer#392]
Is there an option to change the X-Mailer? Every email goes out with:

X-Mailer: nodemailer (1.3.0; +http://www.nodemailer.com; SMTP (pool)/0.1.8[client:1.1.0])

I have some clients that are very picky about this... (I'm already using sendgrid).

**Comment by andris9** [comment]
Use additional mail option

```
{
    from: ....,
    xMailer: false
}
```

**Comment by thenitai** [comment]
Right, so I tried to set it to a custom value. What you are saying it can only be set to "false"?

Thanks.
