### ISSUE TITLE
Can't send mail to google groups mail addresses

### ISSUE THREAD

**Issue by PTihomir** [andris9/Nodemailer#393]
I am not sure if this question should be asked here:
I can't send any mail to googe groups. It was working a week ago, but now those mails just didn't arrive.

I also tried this:
```javascript
smtpTransport.sendMail({
            from: config.from,
            to: private_mail + ',' + group_mail,
            subject: subject,
            html: messagebody
        }, function () ...
```
To my private email the mail arrived, but nothing to google groups mails.

I tried configs, but neither worked:
```javascript
var smtpTransport = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: config.auth.user,
            pass: config.auth.pass
        },
        debug: true
    });

var smtpTransport = nodemailer.createTransport({
        port: 587,
        host: 'smtp.gmail.com',
        requireTLS: true,
        auth: {
            user: config.auth.user,
            pass: config.auth.pass
        },
        debug: true
    });
```

There is no debug info in the console of possible failure.

Thanks in advance for any help

**Comment by andris9** [comment]
If Nodemailer manages to pass the messages to the SMTP server with no errors then thats about it Nodemailer can do. If messages are never received then these probably end up in spam somewhere in transit but this is out of scope for Nodemailer. Try different sending host and different from address. Maybe someone labeled the sender as spam or something.
