### ISSUE TITLE
Nodemailer for io.js cannot sendmail with attachment

### ISSUE THREAD

**Issue by sarahpy** [andris9/Nodemailer#394]
i'm using Nodemailer v0.6.1 and io.js v1.3.0
The code as following >>

var nodemailer = require("nodemailer");
var smtpTransport = nodemailer.createTransport("SMTP",{
        host: "outmail.abc.com", // hostname
        secureConnection: false, // use SSL
        port: 25, // port for secure SMTP
        auth: {
            user: "abc@abc.com",
            pass: "abcpass"
        },
        debug: false, //debug nodemailer
});

var mailOptions = {
        "from":"xxx@abc.com",
        "to":"yyy@abc.com",
        "cc":"",
        "attachments":[{
                "fileName":"Doc1.pdf",
                "filePath":"E:/test/path/upload/test.pdf"
        }],
        "subject":"Test iojs sendmail",
        "html":"<p>PS. Please suggest the solution for me</p>\n"
}

smtpTransport.sendMail(mailOptions, function(error, response){
        if(error){
            console.log(error.message);
            res.send(500);
            //res.send(error.message);
            return;
        }else{
            console.log("Message sent: " + response.message);
            // if you don't want to use this transport object anymore, uncomment following line
            socketTimeout: 30 * 1000 // 0.5 min: Time of inactivity until the connection is closed
            smtpTransport.close(); // shut down the connection pool, no more messages
            res.send(200);
        }

        // if you don't want to use this transport object anymore, uncomment following line
        smtpTransport.close(); // shut down the connection pool, no more messages
    });

Everytime i attach some file in email, the email will not be send and also no error shown. 

But when i use node to run the code, email was send perfectly.

I've debug almost everywhere, both nodejs and iojs calling the same function except that iojs did not return to smtpTransport.sendMail function to notify error or any success.

Any suggestion??

**Comment by andris9** [comment]
Nodemailer supports iojs since v1.3 and I have no plans of fixing earlier versions.
