### ISSUE TITLE
Pass oauth2 token instead of generator

### ISSUE THREAD

**Issue by epaminond** [andris9/Nodemailer#395]
How can I pass xoauth2 token instead of generator? I already have it generated before I send mail. It seems there was `XOAuthToken` option previously (it's mentioned in 0.7 docs) but this doesn't seem to work.

**Comment by andris9** [comment]
The *xoauth2* property can either be a generator or a token, so you should just pass your token as the value of *xoauth2*, no need to use generators there.

**Comment by andris9** [comment]
To be clear - you need to pass base64 encoded XOAUTH2 token, not OAuth2 access token if you do not use the generator. See details of how to convert access token to a base64 encoded xoauth2 token here: https://developers.google.com/gmail/xoauth2_protocol#the_sasl_xoauth2_mechanism

**Comment by epaminond** [comment]
I've tried that but it didn't work. However passing oauth2 access token along with `user` attribute works fine. It looks like `SMTPConnection.prototype._handleXOauth2Token` of smtp-connection module uses it's `_buildXOAuth2Token` method to encode token so my token could be encoded twice.
