### ISSUE TITLE
Config send by mail kuikoo?

### ISSUE THREAD

**Issue by ga12ru12** [andris9/Nodemailer#398]
I want to config to send mail by kuikoo. This is my config:
```javascript
var transporter = nodemailer.createTransport({
    host: 'smtp.kuikoo.com',
    port: 465,
    secure: true,
    auth: {
        user: 'user',
        pass: 'pass'
    }
});
```
When i send mail, There is a error : "[Error: SELF_SIGNED_CERT_IN_CHAIN]". Anyone can help me pls?

**Comment by andris9** [comment]
This is because the server uses self signed certificate which is not allowed by default for security reasons. If you want to bypass this, use additional config option `tls`

```javascript
var transporter = nodemailer.createTransport({
    host: 'smtp.kuikoo.com',
    port: 465,
    secure: true,
    auth: {
        user: 'user',
        pass: 'pass'
    },
    tls: {
        rejectUnauthorized: true // allow invalid certificates
    }
});
```

**Comment by ga12ru12** [comment]
@andris9 i tried but it have error:
```javascript
{ [Error: Invalid login]
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8 http://support.google.com/mail/bin/answer.py?answer=14257 bw3sm4508881pbb.9 - gsmtp',
  responseCode: 535 }
```
I want to use mail kuikoo but why there is google support?

**Comment by ga12ru12** [comment]
@andris9 I have check account mail but user and password is very correct. Why invalid login? :(

**Comment by andris9** [comment]
This is a response from Gmail, are you sure you do not have the host set as `smtp.gmail.com`, or the `service` property set as `gmail`?

**Comment by ga12ru12** [comment]
sorry that's my fault. This is error when i try:
```javascript
{ [Error: Can't send mail - all recipients were rejected]
  code: 'EENVELOPE',
  response: '553 5.7.1 <wrtw@tyuty.tyu>: Sender address rejected: not owned by user request@qupworld.com',
  responseCode: 553 }
```
