### ISSUE TITLE
Being able to send emails with the sender of my choice

### ISSUE THREAD

**Issue by AntouanK** [andris9/Nodemailer#399]
Hi.

This is not an issue but more like a question.

I tried the nodemailer and I saw that it's very easy to use the module to send emails without any authentication.

For example: 
```js
transporter = nodemailer.createTransport();

transporter.sendMail({
    from:     'MY_EMAIL_1@gmail.com',
    to:       'MY_EMAIL_2@gmail.com',
    subject:  'test',
    text:     'test'
  });
```
I can log into my second gmail account and see that I got an email from my first gmail account!
And it seems perfectly valid.
But I never authenticated nodemailer to send that email as `MY_EMAIL_1@gmail.com`.
How is that possible?

**Comment by andris9** [comment]
That's how email works, you can use any `from` and `to` addresses you like, there's nothing Nodemailer specific in it. You only need to authenticate yourself if you want to use Gmail infrastructure to send out the message. If you do not specify outgoing server information then your own computer is going to be the sending server. For receiving messages, no authentication is needed.

**Comment by AntouanK** [comment]
@andris9 Thanks for clearing this out.

So I can use another server to send messages through, but I can also send them myself.

I guess what nodemailer does is that it checks the domain ( in the example `gmail.com` ) and the sends it at port 25, right?
And that won't work for all domains I guess, and that's why you need a provider to do that for you... ( I guess )

**Comment by andris9** [comment]
If you configure the server, then the configured server is going to act as the MSA (mail submission agent) – you pass all your outgoing mail to this MSA and forget about it, the MSA does the actual delivery itself. If you do not configure the outgoing server, then Nodemailer runs as MTA (mail transfer agent) and does the dlivery. When you try to send an email, Nodemailer resolves the MX hostnames for the recipients and connects to port 25 of these hosts. This approach works for all domains but it is highly discouraged as you server is not as trustworthy than Gmail MTA for example – if the sending server isn't actually Gmail then the risk of ending up in the Spam folder is way more higher.

**Comment by AntouanK** [comment]
Got it.

Thanks a lot.
