### ISSUE TITLE
Can we set timing while sending email using sendMail method

### ISSUE THREAD

**Issue by AP25** [andris9/Nodemailer#403]
I am using nodemailer send Mail method and setting headers as

var mailOptions = {
    from: 'Fred Foo ✔ <foo@blurdybloop.com>', // sender address
    to: 'bar@blurdybloop.com, baz@blurdybloop.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world ✔', // plaintext body
    html: '<b>Hello world ✔</b>' // html body
    headers : {
       date : new Date().getTime()
}
};
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        console.log(error);
    }else{
        console.log('Message sent: ' + info.response);
    }
});

But while fetching mails using inbox module i am no getting same date & time in headers.So how we can set time while sending mail

**Comment by andris9** [comment]
IMAP has two date values. One is INTERNALDATE which indicates the time the message was received and the other is the Date header of the message. You have to specifically ask for the Date header using `BODY[HEADER.FIELDS (DATE)]` query – the value you usually get from IMAP is INTERNALDATE. So the date values can not match – there's always some kind of delay between when the message was generated and when it was sored to the recipients server.

**Comment by AP25** [comment]
Thank you!!!! what is INTERNALDATE date value ? Can we set the time of send mail using this ?

**Comment by andris9** [comment]
This value is set by the server and can not be changed in any way https://tools.ietf.org/html/rfc3501#section-2.3.3

**Comment by AP25** [comment]
Ok .thank you!!!
