### ISSUE TITLE
Structured format for specifying e-mail addresses

### ISSUE THREAD

**Issue by chrisveness** [andris9/Nodemailer#404]
As far as I can see from the documentation, this isn't currently possible (and hasn't been suggested), and as far as I can see it should be feasible.

Rather than coding e-mail addresses as strings with angle brackets for the address, it would be good to be able to use arrays of strings / objects for the address/name.

For instance:
````JavaScript
transporter.sendMail({
    from: { 'foo@blurdybloop.com': 'Fred Foo ✔' },
    to: [ 
        'foobar@blurdybloop.com', 
        { 'bar@blurdybloop.com': 'Ноде Майлер' }, 
        { 'baz@blurdybloop.com': 'User Name' } 
    ],
    subject: 'hello',
    text: 'hello world!'
});
````

This way, if you had an array of e-mail names & addresses (for instance, from a database), such as
````JavaScript
var toList = [ 
    { firstname: 'Ноде', lastname: 'Майлер', email: 'bar@blurdybloop.com' },
    { firstname: 'User', lastname: 'Name',   email: 'baz@blurdybloop.com' }
];
````
then generating the 'to'/'cc'/'bcc' emails would be as simple as:
````JavaScript
var to = toList.map(function(record) { 
    var email = {}; 
    email[record.email] = record.firstname+' '+record.lastname; 
    return email;
});
````

**Comment by andris9** [comment]
I see your point but Nodemailer already supports a structured address (`{name, address}`) and I do not want to support too many different kind of structures. Your example could be used with current Nodemailer like this:

```javascript
var to = toList.map(function(record) { 
    return {
        name: record.firstname+' '+record.lastname,
        address: record.email
    };
});
```
