### ISSUE TITLE
attachments not working?

### ISSUE THREAD

**Issue by joseph-jja** [andris9/Nodemailer#407]
I'm doing attachments: [ { path: 'path to file' } ] in the options and it does not work.  If I take that out the email gets sent.  With it in, I see nothing.  It also does not error out.  Is there some size limit?  Attachments are about 2.5 meg.  Is this just happening all async and the attachments are on their way out?

**Comment by andris9** [comment]
Here's an example script how to send attachments: https://github.com/andris9/Nodemailer/blob/master/examples/full.js (assuming you are using Nodemailer version 1.x and not 0.x). Check the `error` and `info` arguments of the `sendMail` callback, you can find the information about the status of the message from these variables.

**Comment by joseph-jja** [comment]
Actually the issue turned out to be that if the smtp  server needs auth and it is empty then it  fails silently and the callback was never called.  Then no error was thrown.  I ended up putting in a console log to see what the communication was.  I'm on 1.0.  

Also how does one know when the mail had been sent? Is there an event to listen to? I'm doing a video email thing and I end up with to many emails at once and need to que then up.  Having an event that I can identify when mail is sent would let me add that in.

**Comment by joseph-jja** [comment]
Ok, nevermind.  It's just taking forever to send the attachments because of my uplink speed and size of attachments.
