### ISSUE TITLE
email services app

### ISSUE THREAD

**Issue by shtefcs** [andris9/Nodemailer#408]
Hi there,

Do you think this code can be used to create Sass apps like mailchimp and others ? I mean to use SeS AWS.

Stefan

**Comment by andris9** [comment]
Could you elaborate, I don't think I understood the issue? You want to send mass emails through AWS SES? Shouldn't be a problem.

**Comment by shtefcs** [comment]
Hi Andris

Tnx for replay and sorry for poor explanation. Yes that's the one thing I want. But just wanted to be sure can it be upgraded to become Email marketing app ? Like if I integrated template builder, stats for **opened emails, clicks, bounced emails and other analytic**.

**Comment by andris9** [comment]
Yes you can do this, but it is way out of scope for Nodemailer. Nodemailer is just a transport for delivering a message from an application to a SMTP relay or MTA. Nodemailer does not keep count of bounces etc. you need to do all this yourself.

**Comment by shtefcs** [comment]
Does  SeS give that insight data ?
