### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by derekriebau** [andris9/Nodemailer#409]
Looking for some insight into an error I'm getting. 

on transporter.sendmail(func(err, info){}), the err variable returns this:

{ [Error: getaddrinfo ENOTFOUND smtp.gmail.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'smtp.gmail.com' }

I don't see any error documentation for nodemailer, and I haven't found anything useful on Google searches. I am trying to send about 50 emails once a week through a cron job. 

I have tried this with and without the nodemailer-smtp-pool package, and my transporter currently looks like this:

var transporter = nodemailer.createTransport(smtpPool({
  service: 'gmail',
  auth: {
    user: 'xxx@gmail.com',
    pass: 'xxx'
  },
  maxConnections: 5,
  maxMessages: 200
}));

I am not using XOATH yet, because I'm not under the impression that I need to. I have removed the DisplayUnlockCaptcha for the gmail account I'm using, but I don't think that's related. 

Any insight is appreciated

**Comment by andris9** [comment]
ENOTFOUND means that the app was not able to resolve DNS A record for *smtp.gmail.com*. Probably something wrong with your DNS server. This is handled by Node and not by Nodemailer, there's nothing Nodemailer can do if a hostname is not resolved. If this happens randomly then you could edit your application to try again in a moment.

**Comment by gelinger777** [comment]
just for those who could be having this error. Please check that you did not copy by mistake a white-space before or after the value of the SMTP server host. In that case DNS resolver fails. It would be good to add some trimming cleaning on that variable.

**Comment by mukeshkbc** [comment]
Another possible cause for this kind of error is the use of **`@`** in the gmail password set for the gmail SMTP. 
Changing the gmail password by removing **`@`** solves the issue in such case.

**Comment by chapagain** [comment]
Another possible cause for this kind of error is the use of **`@`** in the gmail password set for the gmail SMTP.
Changing the gmail password by removing **`@`** solves the issue in such case.

**Comment by BenjamimEterino** [comment]
> just for those who could be having this error. Please check that you did not copy by mistake a white-space before or after the value of the SMTP server host. In that case DNS resolver fails. It would be good to add some trimming cleaning on that variable.

You saved my day.
The problem was really a white-space after the host name

**Comment by john-mbone** [comment]
> just for those who could be having this error. Please check that you did not copy by mistake a white-space before or after the value of the SMTP server host. In that case DNS resolver fails. It would be good to add some trimming cleaning on that variable.

Thank you, I had debugged for almost 2hrs before seeing the white-space

**Comment by qhkm** [comment]
> Another possible cause for this kind of error is the use of **`@`** in the gmail password set for the gmail SMTP. Changing the gmail password by removing **`@`** solves the issue in such case.

Thank you! The issue was the char @ in my password. Fixed it after I changed to password to something else
