### ISSUE TITLE
Include To/CC but don't send them 

### ISSUE THREAD

**Issue by geraintluff** [andris9/Nodemailer#410]
As far as I understand, if I specify an email like:

```javascript
transport.sendMail({
    to: ["me@example.com", "other@example.com"],
    cc: ["third@elsewhere.com"],
    ...
});
```

then it will send the email to those three addresses.  Is there a way to *only* send to `me@example.com`, but to still include the other recipients in the headers?

From my (probably not rock-solid) understanding of SMTP works, this should be possible, at least in the "direct sending" case, because while the list of recipients is included in the payload's headers, the mailboxes in question are specified during the SMTP interaction.

**Comment by andris9** [comment]
You can do this by providing your own SMTP envelope – by default the envelope is generated from the message headers. See [SMTP envelope](https://github.com/andris9/Nodemailer#smtp-envelope) in the docs for details.

In your example it would look like this:

```javascript
transport.sendMail({
    to: ["me@example.com", "other@example.com"],
    cc: ["third@elsewhere.com"],
    envelope: {
        from: 'sender@address',
        to: 'me@example.com'
    }
    ...
});
```

**Comment by geraintluff** [comment]
Fantastic, thanks!

That's embarrassingly obvious now I've seen it. :)
