### ISSUE TITLE
need to use nodemailer to generate eml file

### ISSUE THREAD

**Issue by tajinder** [andris9/Nodemailer#411]
hi
we are using nodemailer to send emails, now we have a requirement to check the size of mail. is it possible somehow with nodemailer ? May be generate eml file and get size of that file. But I couldn't find a way in nodemailer to generate eml file.

**Comment by andris9** [comment]
You can do this with the help of [nodemailer-stub-transport](https://github.com/andris9/nodemailer-stub-transport#usage). See the `info.response` value that contains the eml as a Buffer

**Comment by tajinder** [comment]
thanks !!!
