### ISSUE TITLE
attachments use Chinese filename

### ISSUE THREAD

**Issue by youqingkui** [andris9/Nodemailer#416]
```
attachments: {
      filename: 'Sass 基础教程.txt',
      path: 'Sass 基础教程/Sass 基础教程.txt'
    }
```
Received mail attachment is Unknown  (81.47K)
filename not support UTF8?

![image](https://cloud.githubusercontent.com/assets/7046903/7129277/b53859b4-e290-11e4-8d2c-4358798b7697.png)

**Comment by andris9** [comment]
I can not confirm. If I use the same settings I get a valid filename. For example this is what Gmail shows me:

![](https://cldup.com/TIFHOtXmEu.png)

And if I look at the message source, the attachment header includes a valid [RFC2231](https://tools.ietf.org/html/rfc2231) defined unicode filename:

```
Content-Disposition: attachment;
 filename*0*=utf-8''Sass%20%E5%9F%BA%E7%A1%80%E6%95%99;
 filename*1*=%E7%A8%8B.txt
```

**Comment by youqingkui** [comment]
Perhaps the reason I use the QQ mailbox, I try to change the mail, thank you!

**Comment by andris9** [comment]
This has been updated in v1.6.0. Nodemailer now uses QQ compatible filename headers
