### ISSUE TITLE
email is sent twice

### ISSUE THREAD

**Issue by MyNameIsNotReal** [andris9/Nodemailer#419]
Hi 

Just installed nodemailer yesterday  ("nodemailer": "~1.3.4" ) and find if I am sending an email to two receipt email addresses, it will send two emails to each receipt.  ( 4 email in total).

The following is the code, could you please see if this is a bug or there is something I am doing wrong. 

```

exports.sendEmail = function(){

var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    service: 'sendgrid',
    auth: {
        user: username,
        pass: password 
    }
});
    var options ={};
    options.from = 'example@example.com';
    options.subject = 'Hello';
    options.html = "<!DOCTYPE html><html><head></head><body></body></html>";
    options.to = ['example1@example.com','example2@example.com'];
    console.log('sending email now ');
    transporter.sendMail(options,function(error,info){

        if(error){
            console.log(error);
        }else{
            console.log('Message sent: ' + info.response);
        }
    });
};
```
I made sure it only called once. the following is the log
```
sending email now  
Message sent: 250 Delivery in progress
Message sent: 250 Delivery in progress

```

**Comment by MyNameIsNotReal** [comment]
Sorry, the code is not cl

**Comment by andris9** [comment]
I can't confirm. Using the exact same code snippet (with auth and recipient information changed) I get the following output as expected:

```
sending email now 
Message sent: 250 Delivery in progress
```

Try to come up with an example that always fails, otherwise I can't check what is wrong as right now it seems to be working perfectly.
