### ISSUE TITLE
Content-Transfer-Encoding is not quoted-printable by default

### ISSUE THREAD

**Issue by devinus** [andris9/Nodemailer#420]
The docs state:

> - **encoding** - optional transfer encoding for the textual parts (defaults to 'quoted-printable')

But during our tests using SendGrid, we were able to confirm that this setting was not enabled by default.

**Comment by andris9** [comment]
Yes, you're right, it seems to be a copy-paste from the docs of earlier version of Nodemailer where quoted-printable was used as the default. Fixed with 7dbda614cacb146c86014c5db5c3b9888394cf37

**Comment by motdotla** [comment]
:+1:
