### ISSUE TITLE
Emails are being queued : SMTP reply code 250 

### ISSUE THREAD

**Issue by pranavpunjabi** [andris9/Nodemailer#422]
I receive this reply code when I try to send emails. Also, the receiver is not getting any emails since the message is queued according to the reply code.

```
Message sent: 250 2.0.0 Ok: queued on smtp3m.mail.yandex.net as 1430081058-6ltgNFKSir-iHEKdOrm
```

This did not occur previously and there haven't been any significant changes in the code.

Is this an issue with the email service provider or the usage of the API?

**Comment by andris9** [comment]
This is expected behavior, 250 is SMTP success code for an accepted message
