### ISSUE TITLE
Alternatives not working on SMTPpool Transport

### ISSUE THREAD

**Issue by soitgoes** [andris9/Nodemailer#424]
When using the smtpPool Transport like so alternatives are not included.

var mailer = require('nodemailer');
var smtpPool = require('nodemailer-smtp-pool');
var alternatives = [{contents:"contents of alternative", contentEncoding:"7bit"}];
var smtpTransport = mailer.createTransport(smtpPool(config));

var message = {
      from: "someguy@somewhere.com",
      to: "destination@somedestination.com",
      subject: "Hello World",
      html: "html",
      alternatives:alternatives,
    };
   
smtpTransport.sendMail(message);

**Comment by soitgoes** [comment]
From looking through the source.  It looks like message is supposed to be a mailcomposer object.  However if I pass it as a mailcomposer object it doesn't know how to get the to off of it.  When considering how to fix this I built a mailcomposer object and passed it into the transport but that doesn't appear to work.

So would you prefer to refactor so that the sendMail method on the transport can accept a mailcomposer object properly or would you prefer to have the documented alternatives property respected?

**Comment by andris9** [comment]
You are using `contents` but it should be `content`, try changing this and see if it starts working
