### ISSUE TITLE
Encoding username & password

### ISSUE THREAD

**Issue by funnybones** [andris9/Nodemailer#425]
Hello, 
Is there an option to encode the username and password for the smtp transport ?
I would like to have smtp like : 
 auth: {
                user: 'bm8tcmVwbHk=',
                pass: 'QVRhdGF0QTE='
            }

Thanks.

**Comment by andris9** [comment]
Whats the reasoning for this?

**Comment by funnybones** [comment]
Security, I would like to have the info encoded while sent over the www :) 
Thanks for answering.

**Comment by andris9** [comment]
Using base64 does not enhance security. If you want to protect your credentials, use only TLS encrypted connections to the server (eg. these servers that listen on port 465 and start connections with TLS or these servers that listen on other ports but support the STARTTLS extension).
