### ISSUE TITLE
Example given is not working !

### ISSUE THREAD

**Issue by TheGhostJoker** [andris9/Nodemailer#426]
Hello,
I am having a problem that whenever I run the code below on Node.js it just doesn't work,
even though I have taken this from the  example mentioned on your website.I just want some help on how to make this code work.

The code:
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: '#',
        pass: '***'
    }
});
transporter.sendMail({
    from: '#',
    to: '##',
    subject: 'hello',
    text: 'hello world!'
});

Note: I have not mentioned any of the data in the variables to prevent spamming to my email,but the real code has these variables correctly filled out.

**Comment by awsp** [comment]
This is what I got, 
I think Gmail blocks it and force user login using Browser. 
You can login to Google and visit https://www.google.com/settings/security/lesssecureapps, turn on 
**Access for less secure apps**

Note: That will lower the security level of your Gmail account and makes your account more vulnerable. Maybe there could be a workaround soon? I guess...

**Comment by andris9** [comment]
Here's a note about using Gmail: https://github.com/andris9/Nodemailer#using-gmail

**Comment by TheGhostJoker** [comment]
Hey, just wanted to know, is this restriction also present in live or yahoo accounts.

**Comment by andris9** [comment]
Yahoo is less strict but it would be wise to not use a commodity e-mail provider but a dedicated sender like Sendgrid or Mailgun which all have free tiers available

**Comment by TheGhostJoker** [comment]
Thanks !
