### ISSUE TITLE
Can't use module config to get transport options

### ISSUE THREAD

**Issue by alanhoff** [andris9/Nodemailer#428]
This code above do not work:

```javascript
var nodemailer = require('nodemailer');
var config = require('config');

var transport = nodemailer.createTransport(config.get('mail.server'));
console.log('This won't log nor throw an error');
```

I need to clone my config options to get nodemailer working again:

```javascript
var mout = require('mout');
var nodemailer = require('nodemailer');
var config = require('config');

var options = mout.lang.clone(config.get('mail.server'))
var transport = nodemailer.createTransport(options);
```

**Comment by andris9** [comment]
Could you provide the structure of the config file as well?

**Comment by alanhoff** [comment]
The config module returns a read-only object, and smpt-transport was trying to change it. I [made a pull request][0] to fix this.

[0]: https://github.com/andris9/nodemailer-smtp-transport/pull/13
