### ISSUE TITLE
How to send emails in bulk?

### ISSUE THREAD

**Issue by kikar** [andris9/Nodemailer#429]
I wanna use Nodemailer to send email to my subscribers, but I have a few problem understanding the suggestions:
1) Can I use nodemailer-smtp-pool with nodemailer-ses-transport?
2) How can I use RabbitMQ or a queue manager with nodemailer?

Would be useful to post an example of usage.
Thanks for your time

**Comment by andris9** [comment]
You have to use either nodemailer-smtp-pool or nodemailer-ses-transport but not both. SMTP pool is probably faster but you might try the both out. Using RabbitMQ or any other queue solution is out of scope of Nodemailer, you have to come up with an actual solution yourself
