### ISSUE TITLE
keepBcc option?

### ISSUE THREAD

**Issue by bradvogel** [andris9/Nodemailer#433]
Would you be open a PR to add an option to preserve BCCs? It would simply pass the keepBcc option through to BuildMail. This also parallels MailComposer and BuildMail.

**Comment by bradvogel** [comment]
I also realize that transports can call `mail.message.keepBcc = true` before calling `mail.message.createReadStream()`. Is this intended use?

**Comment by andris9** [comment]
If you use a custom transport then yes. For example this is how the sendmail transport handles bcc: https://github.com/andris9/nodemailer-sendmail-transport/blob/master/src/sendmail-transport.js#L61

**Comment by bradvogel** [comment]
I see. That works for me. Thanks!

**Comment by Nokel81** [comment]
How is this usable for publishing something to nam which requires nodemailer? Where would I put the option if I would want to do this?

**Comment by rokibhasan2** [comment]
can anybody help me to verify my paypal account?
