### ISSUE TITLE
"Connection closed unexpectedly" in nodemailer v0.7.1 sending from gmail to yahoo

### ISSUE THREAD

**Issue by thegreatmichael** [andris9/Nodemailer#435]
I will need to send at most 20 messages per day through nodemailer (using gmail). I am using code like this:
```javascript
    function thatGetsCalledInAnArrayDotForEach (participant) {
      var smtpTransport = nodemailer.createTransport("SMTP", {
        service: "Gmail",
        auth: {
          XOAuth2: {
            user: "my institutional gmail", 
            clientId: "blahblahblah.apps.googleusercontent.com",
            clientSecret: "gobbldygook",
            refreshToken: "somenoncense"
          }
        }
      });
      var mailOptions = {
        from: "my institutional gmail",
        to: participant.email,
        subject: "My subject",
        generateTextFromHTML: true,
        html: 'My message containing html ' + participant.someField + " s'more text"
      };
      smtpTransport.sendMail(mailOptions, function(error, response) {
        if (error) {
          console.log("error sending a message", mailOptions, error, response);
        } else {
          console.log(response);
        }
        smtpTransport.close(); //should i do close here? the
      });
    }
```

 Right now I'm sending 8, and the 6th (but none of the others?!) is failing with:

    error sending a message { from: 'my institutional gmail',
      to: 'acorrectaddress@yahoo.com',
      subject: 'My subject',
      generateTextFromHTML: true,
      html: 'My message containing html',
      transport:
       { options:
          { service: 'Gmail',
            auth: [Object],
            maxConnections: 5,
            transport: 'SMTP',
            host: 'smtp.gmail.com',
            secureConnection: true,
            port: 465,
            requiresAuth: true,
            domains: [Object],
            maxMessages: Infinity },
         transportType: 'SMTP',
         dkimOptions: false,
         transport: { options: [Object], pool: [Object] },
         version: '0.3.35',
         sendMail: [Function] },
      text: 'My message containing html' } { [Error: Connection closed unexpectedly] stage: 'mail' } undefined

Anyone have any suggestion or way I can get more details about the error?

**Comment by andris9** [comment]
If sending fails in the mail stage then you could just try again until it succeeds. You could also set `debug` option to true for the  to see the SMTP transaction log which should give a better understanding of why it fails:

```
nodemailer.createTransport("SMTP", {
        service: "Gmail",
        debug: true,
        ....
```

**Comment by andris9** [comment]
Closing as v0.7 is not supported anymore
