### ISSUE TITLE
What happens when SMTP Server returns a 454?

### ISSUE THREAD

**Issue by karli2000** [andris9/Nodemailer#436]
Hi,

first of all: great that you make Nodemailer!

We are using Nodemailer (with smtp-pool) to send bursts of emails to our user when something happens, this means we need the highest throughput possible. We use AWS SES and right now we have a rate limit of 200 messages/seconds. When our system with Nodemailer sends more than 200 messages/second AWS SES returns:
454 Throttling failure: Maximum sending rate exceeded
(as described here: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/reach-sending-limits.html )

And it looks like that Nodemailer is not reacting on this, so the message is getting lost, or am i wrong?

Thank you,
Max

**Comment by andris9** [comment]
I added `rateLimit` option in nodemailer-smtp-pool v1.1.0. Set this value under 200 and see if it helps.

**Comment by karli2000** [comment]
Great! 
I will test it and tell you if it works.

**Comment by karli2000** [comment]
I tested it and something strange is happening:
Without a rateLimit i can get up to 280 messages/second (AWS SES allow to go over the limit for a short period of time) on my test-machine.

With a rateLimit (doesn't materr if 200 or 2000) i get only around 130 messages/second, does the timer that you implemented consume so much CPU (i am using node 0.12.3)? Or is there a bug in the ratelimit?

**Comment by andris9** [comment]
Ok, sounds strange, I'll look into it next week when I have time

**Comment by andris9** [comment]
Try the updated nodemailer-smtp-pool v1.1.1 where I fixed a delay calculation issue.

**Comment by karli2000** [comment]
Works perfect! 
I tested it with 60k mails and it hits exactly the ratelimit.
Thank you very much!
