### ISSUE TITLE
Return "ECONNREFUSED"

### ISSUE THREAD

**Issue by lgick** [andris9/Nodemailer#437]
HI! 

It's great work with gmail, but when i enter yandex data Nodemailer return: 

{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

I use: 

```javascript
transport: {
  service: 'smtp.yandex.ru',
  port: 465,
  secure: true,
   auth: {
     user: 'pupkin.vasya.2.0',
     pass: '4rfv5tgb'
  }
}
```

Please help!

**Comment by freestyle21** [comment]
Is the process server not killed?

**Comment by andris9** [comment]
You have `service` and `host` options slightly messed up.

Use either `host` with the domain name:

```
transport: {
  host: 'smtp.yandex.ru',
  port: 465,
  secure: true,
  auth: ...
```

or `service` without `port` and `secure` option:

```
transport: {
  service: 'Yandex',
  auth: ...
```
