### ISSUE TITLE
connection times out

### ISSUE THREAD

**Issue by freestyle21** [andris9/Nodemailer#438]
I tried with the nodemail ， It's not working. Nothing get consoled out. After 30-40s I get:

  
    { [Error: Connection timeout] code: 'ETIMEDOUT' }
    Error: connect ETIMEDOUT
        at errnoException (net.js:904:11)
        at Object.afterConnect [as oncomplete] (net.js:895:19)

Here is my code:

    var nodemailer = require('nodemailer');

    // create reusable transporter object using SMTP transport
    var transporter = nodemailer.createTransport({
        service: 'Gmail',
        auth: {
            user: test@gmail.com',
            pass: 'userpass'
        }
    });

    var mailOptions = {
        from: 'Fred Foo ✔ <test@gmail.com>', // sender address
        to: 'test1@gmail.com', // list of receivers
        subject: 'Hello ✔', // Subject line
        text: 'Hello world ✔', // plaintext body
        html: '<b>Hello world ✔</b>' // html body
    };

    transporter.sendMail(mailOptions, function(error, info){
        if(error){
            console.log(error);
        }else{
            console.log('Message sent: ' + info.response);
        }
    });

Thank you all.

**Comment by andris9** [comment]
If you are using `service: 'GMail'` then check if your firewall allows outgoing connections on port 465

**Comment by PaolaGarcia** [comment]
I have the same problem. But I'm using host: "smtp.office365.com" in port: "587".
I already check the outgoing connection in my port and is allowed from anywhere. Sometimes it does work but only when I just turn on the computer. Then it doesn't work and give me the ETIMEDOUT error. 

I'm using Node v6.2.2, Ubuntu 14.04 and last version of Nodemailer.

Here is my code: 

`
const nodemailer = require("nodemailer");
const smtpTransport = require("nodemailer-smtp-transport");

var smtpTransport = nodemailer.createTransport(smtpTransport({
    host : "smtp.office365.com",
    port: 587,
    auth : {
        user : settings.EMAIL_HOST,
        pass : settings.EMAIL_PASS
    }
}));

var mailOptions={
        from : "test@test.com",
        to : "test@test.com",
        subject : "Send Mail",
        text : "Test"
        
    }
    smtpTransport.sendMail(mailOptions, function(error, response){
        if(error){
            console.log("Message Not Send", error);
        }else{
            console.log("Message sent!");
        }
    });
`

**Comment by yazeedabalkhail** [comment]
Hello @PaolaGarcia , I'm using the same settings as you are .. getting the same problem. Ever found a solution on that?

**Comment by mustafabw52** [comment]
I am also getting same issue here is my code.

```
var transporter = nodemailer.createTransport(
                smtpTransport({
                    host: 'smtp.gmail.com',
                    port: 25,
                    auth: {
                        user: 'helpdesk@ankhor.org',
                        pass: 'ankhorhelp123'
                    },
                    ignoreTLS: true,
                    secure: false,
                    secureConnection: false,
                    requiresAuth: true,
                    domains: ["gmail.com", "googlemail.com"],
                    connectionTimeout: 60000,
                    greetingTimeout: 30000,
                    //maxConnections: 10,
                    debug: true
                })
                );


 transporter.sendMail({
            from: '"ankhor.org"<' + config.site.adminEmail + '>',
            to: options.to,
            subject: options.subject,
            html: options.html,
            fromname: 'ankhor.org'
        }, callback);

can anyone explain what is the issue.
````

**Comment by jpsalvadorm63** [comment]
The gmail account configuration should "**Allow less secure apps: ON**". Then I got the mail in my gmail

But I still get the error:

`Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

**Comment by smendez-hi** [comment]
This still happens. I'm using another mail, not Gmail and I get this error after a few minutes:
```
SERVER 1:
└──421 4.4.2 <mymail> Error: timeout exceeded
Closing connection to the server
```
But i received the email in my inbox. So apparently it works but after a few minutes the server stops.

**Comment by Rkrushanovskij** [comment]
Guys, any updates?

**Comment by okabamac** [comment]
Anyone found a solution?
Here is my code:
import nodemailer from 'nodemailer';
import debug from 'debug';
import keys from './config';
/**
 *@description - A function for sending mail
 *
 * @param {Object} mailData Mail Details
 *
 * @returns {void} void
 */
const mailer = async (mailData) => {
  const {
    to, subject, text, html,
  } = mailData;

  try {
    const transporter = nodemailer.createTransport({
      host: 'smtp.ethereal.email',
      port: 25,
      auth: {
        user: keys.email,
        pass: keys.password,
      },
      tls: {
        rejectUnauthorized: false,
      },
      logger: true,
      debug: false, // include SMTP traffic in the logs
    });
    const info = await transporter.sendMail({
      from: '"NEMSA App " <markokaba99@gmail.com>',
      to,
      subject,
      text,
      html,
    });
    debug('development')('Message sent: %s', info.messageId);
    debug('development')(
      'Preview URL: %s',
      nodemailer.getTestMessageUrl(info),
    );
  } catch (err) {
    debug('development')(err);
  }
};

export default mailer;

**Comment by slothdude** [comment]
Trying to connect to the mailtrap tool I got it to work by changing the port to 2525
```
const mailtrapTransporter = nodemailer.createTransport({
  host: "smtp.mailtrap.io",
  secure: false,
  requireTLS: true,
  port: 2525,
  auth: {
    user: config.MAILER_USER,
    pass: config.MAILER_PASS
  }
});
```

**Comment by DNature** [comment]
Most times this issue is caused by enabling firewall. disable your firewall and try again. reboot your pc if necessary.
It worked for me

**Comment by OleksandrHrinchenko** [comment]
Try
port: 2525,
  secure: false,
  requireTLS: true,

**Comment by OleksandrHrinchenko** [comment]
> Trying to connect to the mailtrap tool I got it to work by changing the port to 2525
> 
> ```
> const mailtrapTransporter = nodemailer.createTransport({
>   host: "smtp.mailtrap.io",
>   secure: false,
>   requireTLS: true,
>   port: 2525,
>   auth: {
>     user: config.MAILER_USER,
>     pass: config.MAILER_PASS
>   }
> });
> ```

Thanks, it works!

**Comment by gada121982** [comment]
> If you are using `service: 'GMail'` then check if your firewall allows outgoing connections on port 465

Thanks you so much !

**Comment by Syed-Sami-Ul-Huda** [comment]
> Most times this issue is caused by enabling firewall. disable your firewall and try again. reboot your pc if necessary.
> It worked for me

thanks a bundle kith, it also worked for me, I wish I see your comment before wasting my 3 precious hours for finding its solution

**Comment by DNature** [comment]
You're welcome :smiley:

**Comment by DNature** [comment]
> thanks a bundle kith, it also worked for me, I wish I see your comment before wasting my 3 precious hours for finding its solution

You're welcome :smile:

**Comment by SurgicalCrow** [comment]
> 
> 
> > If you are using `service: 'GMail'` then check if your firewall allows outgoing connections on port 465
> 
> Thanks you so much !

Hey, i am using 587 port, but where should i allow this port

**Comment by larbisahli** [comment]
@SurgicalCrow sudo ufw allow 465

**Comment by saurav7622** [comment]
> > Trying to connect to the mailtrap tool I got it to work by changing the port to 2525
> > ```
> > const mailtrapTransporter = nodemailer.createTransport({
> >   host: "smtp.mailtrap.io",
> >   secure: false,
> >   requireTLS: true,
> >   port: 2525,
> >   auth: {
> >     user: config.MAILER_USER,
> >     pass: config.MAILER_PASS
> >   }
> > });
> > ```
> 
> Thanks, it works!

**Comment by mk1020** [comment]
in my case, it was necessary to allow the smtp server management console (server scaleway)

**Comment by adilsonfuta** [comment]
In my case, this is my message  error

Error: connect ETIMEDOUT 52.98.16.210:465
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ESOCKET',
  syscall: 'connect',
  address: '52.98.16.210',
  port: 465,
  command: 'CONN'
}


code example:


const transporter = nodemailer.createTransport(
    {

        host: "smtp.office365.com",
        secureConnection: false,
        port: 587,
        auth: {
            user: user_email,
            pass: password
        },
        tls: {
            ciphers: 'SSLv3'
        }

    }
);

**Comment by bangal18** [comment]
https://www.digitalocean.com/community/questions/why-can-t-i-send-emails-in-nodejs-ubuntu-16-04-using-nodemailer

**Comment by noorgohar456** [comment]
Following works for me


var transporter = nodemailer.createTransport({
  host: 'smtp.office365.com',
 // service: 'office365',
  port: '587',
 // secure: 'false',
  auth: {
    user: '',
    pass: ''
  },    
  //secureConnection: false,
 // tls: {
  //    rejectUnauthorized: true
  //}
});

**Comment by devShinigami** [comment]
> I tried with the nodemail ， It's not working. Nothing get consoled out. After 30-40s I get:
> 
> ```
> { [Error: Connection timeout] code: 'ETIMEDOUT' }
> Error: connect ETIMEDOUT
>     at errnoException (net.js:904:11)
>     at Object.afterConnect [as oncomplete] (net.js:895:19)
> ```
> 
> Here is my code:
> 
> ```
> var nodemailer = require('nodemailer');
> 
> // create reusable transporter object using SMTP transport
> var transporter = nodemailer.createTransport({
>     service: 'Gmail',
>     auth: {
>         user: test@gmail.com',
>         pass: 'userpass'
>     }
> });
> 
> var mailOptions = {
>     from: 'Fred Foo ✔ <test@gmail.com>', // sender address
>     to: 'test1@gmail.com', // list of receivers
>     subject: 'Hello ✔', // Subject line
>     text: 'Hello world ✔', // plaintext body
>     html: '<b>Hello world ✔</b>' // html body
> };
> 
> transporter.sendMail(mailOptions, function(error, info){
>     if(error){
>         console.log(error);
>     }else{
>         console.log('Message sent: ' + info.response);
>     }
> });
> ```
> 
> Thank you all.
> 

Downgrade to nodemailer@4.70.0

**Comment by MusabDev** [comment]
I was using Linode and after researching a lot, I came across this community post (https://www.linode.com/community/questions/19082/i-just-created-my-first-linode-and-i-cant-send-emails-why). By default, they block the ports even if I set up the firewalls. So, I created a ticket and they resolved the issue 🎉

**Comment by borhansahed** [comment]
I can't to connect the SMTP server from my local host ! Whenever I trying to test the server from online it works!


 const transport = nodemailer.createTransport({
    host: "smtp.customserver.com",
    port: 25,
    secure: false,
    auth: {
      user: process.env.USER_EMAIL,
      pass: process.env.USER_PASSWORD,
    },
  });

**Comment by folushooladipo** [comment]
Apart from the firewall problems, for some bizarre reason specifying the `service` SMTP transport option is what caused my own `nodemailer` requests to time out. That is, I'm running a Next.js app in Hetzner that uses nodemailer to send emails using Gmails SMTP servers, and when I use this, it works:
```typescript
const options = {
  host: "..."
  port: 587, // ports 25 and 465 are locked by Hetzner until you qualify to have them opened
  secure: false,
  requireTLS: true,
  auth: { user: ..., pass: ... },
}
```

but this doesn't
```typescript
const options = {
  service: "Gmail", // <-- this messes things up. Why? Beats me.
  host: ...
}
```

Very bizarre.

**Comment by rakibdev** [comment]
@folushooladipo 
Using service option seem to override user defined options such as `port: 587` with service presets `port: 465`. https://github.com/nodemailer/nodemailer/blob/master/lib/well-known/services.json#L78

Confirmed by checking logs. `Connection established to 142.251.10.108:587`
![image](https://github.com/user-attachments/assets/7ec6b228-db33-46e7-bde7-420aa64caae8)

If I use `service: 'Gmail'` then `Secure connection established to 142.251.10.108:465`
![image](https://github.com/user-attachments/assets/d449e928-f970-4fc3-a6ff-5aa180669353)
