### ISSUE TITLE
unable to set secure: true?

### ISSUE THREAD

**Issue by riopn** [andris9/Nodemailer#440]
If I don't supply `secure: true`, does this mean authenticating to the smtp server over `587` won't be using STARTTLS or some secure channel?

I'm using gandi mail and this works:

```
var transporter = nodemailer.createTransport({
        "host": "mail.gandi.net",
        "port": 587,
        "auth": {....}
});
```

But when supplying the `secure: true`, I get an error returned:

`routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795`

**Comment by andris9** [comment]
Do not use `secure: true` with port 587. This is a plaintext port, not SSL port.
