### ISSUE TITLE
" Error: Greeting never received" problem

### ISSUE THREAD

**Issue by BigYu** [andris9/Nodemailer#441]
The version:
    "nodemailer": "^1.3.4",

I just tried several different mail service but always have this issue. I turn ssl authentication on, the code is like:
``` 
ssl: true
```
or
```
secureConnection: true
```

I do not know what is the problem :(

**Comment by kytwb** [comment]
Just experienced this as well

**Comment by guovz** [comment]
I also encountered this problem,do not know what is the problem too. :cry:

**Comment by andris9** [comment]
This usually happens when the server expects encrypted connection but you start out as plaintext. To connect to secure servers you should use the following setup (note the `secure` option):

```javascript
var transporter = nodemailer.createTransport({
    host: 'localhost',
    port: 465,
    secure: true,
    auth: {
        user: 'username',
        pass: 'password'
    }
});
```

**Comment by teafn** [comment]
@andris9 it haha ,solved

**Comment by HassanChiang** [comment]
Thank you @andris9

**Comment by karamuka** [comment]
> Just experienced this as well.
> Fixed using `secureConnection: true` and `port: 465`.

This solved it for me

**Comment by carepollo** [comment]
I tried this and not getting `Error: connect ECONNREFUSED 127.0.0.1:465`

**Comment by mamurjon7191** [comment]
CHiqmadi chortlar

**Comment by SurbhiB28** [comment]
> Just experienced this as well. Fixed using `secureConnection: true` and `port: 465`.

I used `secureConnection: true` and it worked for me. Thanks.
