### ISSUE TITLE
SSLv3 issue with iojs and mail server

### ISSUE THREAD

**Issue by alinz** [andris9/Nodemailer#442]
hello, 
I know this issue has been answered multiple times. But nothing has worked for me.
I'm using the latest iojs `2.2.0`. Also, I'm using the latest nodemailer `1.3.4`.
 
none of the following fixes worked for me.

```js
 secure: true,
  tls: {
    rejectUnauthorized: false
  }
```

```bash
NODE_TLS_REJECT_UNAUTHORIZED="0"
```

And here's my error message:

```
Error: 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:769:
```

**Comment by andris9** [comment]
Probably some issue with Node and OpenSSL. You can play around with `tls.secureProtocol` and `tls.ciphers` option to get around this issue

**Comment by alinz** [comment]
Because It took too long to get my answer, I decided to use different project. Thanks anyway!
