### ISSUE TITLE
Can't send 8Mb file

### ISSUE THREAD

**Issue by klimashkin** [andris9/Nodemailer#443]
Hello!
I'm attaching file (Buffer) of 7973142 length, but mail is not sent (smaller files sent ok).
Moreover in this case ```sendMail``` callback never invoked, even with error, so it's hard to find what is the reason.
```
                attachments: [{
                    filename: 'yml_market.xml',
                    contentType: 'text/xml',
                    content: <Buffer ...>
                }]
```
Maybe files with size more then some threshold must be attached in different way?

**Comment by andris9** [comment]
Could you create a self contained example that I could run to verify this error? I'm closing this issue for now as noone else has complained about such behavior
