### ISSUE TITLE
transporter.sendMail(data, cb) never returns to callback fn

### ISSUE THREAD

**Issue by davisford** [andris9/Nodemailer#444]
I am seeing a [weird, intermittent scenario](https://github.com/sendgrid/nodemailer-sendgrid-transport/issues/11) that used to never happen, but now seems to be happening more often.  AFAICT, no changes on my end.  I'm using the Sendgrid transport, and they had some problems last week, but I'm still seeing this happen even today.

Some emails are sent just fine, others never return from this call -- despite the callback being a valid function that always logs, etc.

```
var transporter = nodemailer.createTransport(sendgrid(require(secretPath)));

// later in code 
transporter.sendMail(data, cb)  // cb is never called
```

I'm using `nodemailer@1.3.4` and `nodemailer-sendgrid-transport@0.1.0`

More details are on the issue (linked above) I posted in `nodemailer-sendgrid-transport` -- I **suspect** it may have to do with the fact that I'm using [hyperzip](https://github.com/hyperquest/hyperzip) to stream and attach a PDF to the email from Amazon S3.  Perhaps the stream stalls or something...not sure.

I'm going to tail `netstat` the next time it hangs and try to determine if it is stuck on s3 or if it is actually making an outbound connection to `api.sendgrid.com`

I'm just curious if @andris9 (or anyone else) you have ever seen behavior like this?  I'm filing this more as a exploratory question vs. an issue -- I'm not sure the problem I'm seeing has anything to do with nodemailer, per se...that's just where I leave my own code and it never returns.  Just wondering if you might have some insight before I start digging deeper into the source.

**Comment by davisford** [comment]
Oh, I'm starting to suspect this https://github.com/substack/hyperquest/issues/39

@andris9 feel free to close if you feel this is unrelated, but if you have any insight I would love to hear it.

**Comment by andris9** [comment]
No idea about. I would replace hyperquest with request if request would be about 3MB in size
