### ISSUE TITLE
SMTP with cPanel based emails doesn't work.

### ISSUE THREAD

**Issue by abhishekdgeek** [andris9/Nodemailer#447]
Hi,

Firstly thanks for the great tool you made. I was working on using it with cPanel's email id on shared server. I ended up with these logs

SERVER 1:
└──220-md-in-6.webhostbox.net ESMTP Exim 4.85 #2 Thu, 18 Jun 2015 09:12:14 +0000 
   220-We do not authorize the use of this system to transport unsolicited, 
   220 and/or bulk e-mail.
CLIENT 1:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-md-in-6.webhostbox.net Hello [127.0.0.1] [182.69.86.155]
   250-SIZE 52428800
   250-8BITMIME
   250-PIPELINING
   250-AUTH PLAIN LOGIN
   250-STARTTLS
   250 HELP
CLIENT 1:
└──STARTTLS
SERVER 1:
└──220 TLS go ahead
Connection secured
CLIENT 1:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-md-in-6.webhostbox.net Hello [127.0.0.1] [182.69.86.155]
   250-SIZE 52428800
   250-8BITMIME
   250-PIPELINING
   250-AUTH PLAIN LOGIN
   250 HELP
CLIENT 1:
└──AUTH PLAIN AGluZm9Ac29sb21vZnkuY29tAEI5XlR3P3Zz
SERVER 1:
└──235 Authentication succeeded
CLIENT 1:
└──MAIL FROM:<anonymous@[127.0.0.1]>
SERVER 1:
└──501 <anonymous@[127.0.0.1]>: domain literals not allowed
Gawaksh ka error { [SenderError: Mail from command failed - 501 <anonymous@[127.0.0.1]>: domain literals not allowed]
  name: 'SenderError',
  data: '501 <anonymous@[127.0.0.1]>: domain literals not allowed',
  stage: 'mail' }
Closing connection to the server

Let me know how do I configure this. I am using this setting as of now:

var smtpTransport = nodemailer.createTransport("SMTP", {
    host: "mail.domain.com", // hostname
        secureConnection: false, // TLS requires secureConnection to be false
        port: 587, // port for secure SMTP
        auth: {
            user: "info@domain.com",
            pass: "password"
        },
        debug:true,
        tls: {
            rejectUnauthorized: false
        }
});

Thanks,
Abhishek Jain

**Comment by andris9** [comment]
Check the `from` address. Your server does not allow FROM address that uses domain literals. If you did not define the `from` address, then a default address is generated which might include the domain literal. Make sure that you always use a valid `from` address when sending emails.

**Comment by abhishekdgeek** [comment]
Awesome man! Thanks.

Solution for mean Stack: Just define a mail id in config.mailer.from which is not blocked by cPanel.

**Comment by pozitivexx** [comment]
I have same issue.
Where is the config.mailer.from ?
I changed sender name as Gmail Account name but it doesn't send again.

**Comment by abhishekdgeek** [comment]
@pozitivexx whenever you are sending mails, just make sure you are using right from address.

In below example set mailOptions.from = smtpConfig.auth.user to make sure mail delivers. This is cPanel/Host configuration. Contact hosting partner for more details.

// setup e-mail data with unicode symbols
var mailOptions = {
    from: '"Fred Foo 👥" <foo@blurdybloop.com>', // sender address
    to: 'bar@blurdybloop.com, baz@blurdybloop.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world 🐴', // plaintext body
    html: '<b>Hello world 🐴</b>' // html body
};

**Comment by Inventiveatsquare** [comment]
you will need SSL CONFIG TO MAKE IT PERFECT.

**Comment by richardebrain** [comment]
@abhishekdgeek , how do you check the server logs in cpanel

**Comment by Rohan-mgr** [comment]
@abhishekdgeek 
![Screenshot (126)](https://github.com/nodemailer/nodemailer/assets/78647278/4451a5ac-1368-437d-a02f-d83ffbeac1a5)
![Screenshot (127)](https://github.com/nodemailer/nodemailer/assets/78647278/d9b38d38-6213-45d3-9c58-da11f0c83ba5)
Im still getting error here need help!!

**Comment by Rohan-mgr** [comment]
I'm not getting the error but I'm not receiving the reset email

**Comment by richardebrain** [comment]
is it in development or production , what's the error you get in console ?
