### ISSUE TITLE
Specific header for transport plugin

### ISSUE THREAD

**Issue by kemelzaidan** [andris9/Nodemailer#448]
Hi, I'm trying to build a transport plugin in order to nodemailer to be able to use a certain API as transport. From what I could understand on the documentation, the transport send function doesn't actually dispatches the request to the API, but only streams a _Mailer_ object to nodemailer, who does the real job of sending the request to the API (http://www.nodemailer.com/#plugin-api). There are couple things I couldn't understand:

1. On which property does the API endpoint should be: **data** or **message**? 
2. Another problem is that the API requires the client to send a specific header upon request (_x-auth-token_) with the correct token value for each user. I tried implementing the follwing transport:

```js
var lwTransport = {
    name: 'Locaweb',
    version: require('./package.json').version,
    send: function (mail, callback) {
      email.data = mail
      email.message.setHeader('x-auth-token', process.env.TOKEN)
      email.message.setHeader('User-Agent', 'nodemailer-locaweb-transport')

      var input = email.message.createReadStream()
      var messageId = (email.message.getHeader('message-id') || '').replace(/[<>\s]/g, '')
      input.pipe(process.stdout)
      input.on('end', function () {
        callback(null, {
            messageId: messageId
        })
      })
    }
}
```

What am I doing wrong? The _info_ object that is returning is that:

```js
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

How can I get more feedback to know what is wrong?

**Comment by andris9** [comment]
What kind of API is that you are trying to use? SMTP based or HTTP based? For example here's a transport plugin that generates the raw rfc822 message [stub-transport.js](https://github.com/andris9/nodemailer-stub-transport/blob/master/src/stub-transport.js) (this plugin returns the data to the caller but you could use it to stream to HTTP for example)

**Comment by kemelzaidan** [comment]
It is HTTP based. I'm in doubt if the transport should be responsible to dispatch the post request to the actual HTTP API or leave it to nodemailer...

**Comment by andris9** [comment]
Nodemailer can only give you the raw rfc822 message but your transport plugin needs to deliver it by itself. Nodemailer has no HTTP support.

**Comment by kemelzaidan** [comment]
Thanks! :smile:
