### ISSUE TITLE
Request: Apple Watch Support

### ISSUE THREAD

**Issue by knightcode** [andris9/Nodemailer#450]
According to litmus, including a third section in a mail with `Content-Type: text/watch-html` lets us supply an version of the mail formatted for the Apple Watch.

https://litmus.com/blog/how-to-send-hidden-version-email-apple-watch

**Comment by bradvogel** [comment]
Can't this be done via a plugin? Perhaps a variant of https://github.com/andris9/nodemailer-html-to-text that adds that content type.

**Comment by andris9** [comment]
Added new message option `appleWatch` in v1.4.0

Usage:

```javascript
transport.sendMail({
    text: "Plaintext content",
    html: "HTML content",
    watchHtml: "Apple Watch specific content"
});
```

I do not have an Apple Watch or emulator myself, so this is untested, I have no idea how the watch actually treats this.
