### ISSUE TITLE
Image attachment coming through with no data

### ISSUE THREAD

**Issue by mycompassspins** [andris9/Nodemailer#452]
Hey there,

Despite all the hair I've pulled outta my head over the last few hours, I love nodemailer :) I'm trying to send an image attachment and it's coming through, but with no data. 0kb in size. That's using this code:

    var path = require('path');
    var uploadDir = path.dirname(require.main.filename); 
    // This actually produces a filepath that starts at my /Applications dir on my Mac, but ends in the right spot.

    var img = require("fs").readFileSync(uploadDir + '/uploads/' + params.newFileName);
    // file was upload was handled on the server by multer and renamed to something like this: fc5c5921bd0892f114cd7b6f0d39d9a3.gif

    attachments: [{
        filename: params.newFileName,
        filePath: img
    }]

I've tried about a hundred variations on the theme based on my research online, and either I get no attachment at all, the result outlined above, or a generic attachment-1.bin. I would sure love some guidance :)

**Comment by andris9** [comment]
Instead of filePath:img use path:'/path/to/file'

**Comment by mycompassspins** [comment]
I appreciate the reply, but I've tried that also, to no avail.

**Comment by andris9** [comment]
There are several options to set the contents of the attachment. One is to use `path: fullpath` to load the file from the filesystem. The other is to provide `content: Buffer` if you have loaded the file already into a variable. See all options [here](https://github.com/andris9/Nodemailer#attachments)

**Comment by sschwartzman** [comment]
I seem to be running into the same issue. I've tried various ways to attach a .png file and all come back with a blank file, regardless if im trying to embed it inline to the html or not.

**Comment by mycompassspins** [comment]
Finally got it to work like this:

    var path = require('path');
    var uploadDir = path.dirname(require.main.filename); 
    var img = require("fs").readFileSync(uploadDir + '/uploads/' + params.newFileName);

    attachments: [{
        filename: params.newFileName,
        content: new Buffer(img)
    }]

Thanks for pointing me in the right direction.
