### ISSUE TITLE
Same issue as in #452: Image attachment coming through with no data

### ISSUE THREAD

**Issue by sschwartzman** [andris9/Nodemailer#453]
Hi Andris,

I'm running into the same issue that was mentioned yesterday in issue #452 . It seems pretty straightforward to attach a png file, and I have tried several of the ways listed in your doc. Each one returns a blank png. I am sure this png exists and is valid, so I don't know what I'm missing.

Here is the snippet of my latest attempt:

```javascript
var mailOptions = {
    from: 'redacted',
    to: 'redacted',
    subject: 'Yay!',
    text: 'I can totally send images like this!',
    html: '<b>I can totally send images like this!</b><br><br>
        <img src="cid:someImage@redacted.com"/>',
    attachments: [{
        path: '/Users/seth/selenium/image.png',
        cid: 'someImage@redacted.com'
    }]
};

transporter.sendMail(mailOptions, function(error, info) {
    if(error) {
        return console.log(error);
    }
    console.log('Message sent: ' + info.response);
});
```

Thanks,
Seth

**Comment by sschwartzman** [comment]
@mycompassspins Any luck with this issue on your end?

**Comment by sschwartzman** [comment]
Nevermind, got it to work!

**Comment by mycompassspins** [comment]
@sschwartzman, I haven't figured it out yet. What was your solution?

**Comment by appshore** [comment]
attachments: [{
        path: '/path/to/image.jpg'
    }]
isn't working

    attachments: [{
        filename:'image.jpg'
        path: '/path/to/image.jpg'
    }]
is working.
