### ISSUE TITLE
"535 Authentication Failed" when using Zoho

### ISSUE THREAD

**Issue by brentcklein** [andris9/Nodemailer#456]
I recently migrated from Gmail to Zoho for my app using `"nodemailer": "~0.3.28"`, and I'm having trouble authenticating with Zoho's SMTP server.  Here's the log output:

```
SERVER 1:
└──220 mx.zohomail.com SMTP Server ready July 7, 2015 8:18:44 AM PDT
CLIENT 1:
└──EHLO [127.0.0.1]
SERVER 1:
└──250-mx.zohomail.com Hello [127.0.0.1] (cpe-xx-xxx-xxx-xxx.kya.res.rr.com (xx.xxx.xxx.xxx))
CLIENT 1:
└──AUTH PLAIN c3VwcG9ydEBlbWFpbC5jb21zdXBwb3J0QGVtYWlsLmNvbXBhc3N3b3Jk
SERVER 1:
└──250-AUTH LOGIN PLAIN
CLIENT 1:
└──MAIL FROM:<support@email.com>
SERVER 1:
└──250 SIZE 25000000
CLIENT 1:
└──RCPT TO:<me@email.com>
SERVER 1:
└──535 Authentication Failed
sendMail error: [object Object]RecipientError: Can't send mail - all recipients were rejected
{ [RecipientError: Can't send mail - all recipients were rejected] name: 'RecipientError' }
Closing connection to the server
SERVER 1:
└──250 Sender <support@email.com> OK
```

I changed the outgoing and incoming email addresses above, but in the actual output they're all as they should be: the sender is correct, the password in the auth header is correct, and the recipient email is valid.  

Here's my setup:

```
var auth = { user: 'support@email.com', pass: 'password' };
var smtpTransport = nodemailer.createTransport('SMTP', {
	service: "Zoho",
	auth: auth,
	debug: true
});
var mailOptions = {
	from: 'Support <' + auth.user + '>',
	to: 'me@email.com,
	subject: subject,
	text: body,
	html: body
};
	
// send mail with defined transport object
smtpTransport.sendMail(mailOptions, function(error, response){
	if(error){
		console.log('sendMail error: ' + auth + error);
		if(callback){
			callback(error,null);
		}
        }else{
		console.log("Message sent: " + response.message);
		if(callback){
			callback(null,response);
		}
	}
});
```

I'm able to connect to Zoho via SMTP using the Mac Mail app, and through a gmail account, so there must just be something wrong with my configuration; but the only thing I've changed since migrating to Zoho is the `service` parameter and the `{user: ..., pass}`, so I have no idea what I could be doing wrong.  I've spoken to Zoho tech support, and they just made sure I had the right port number and was using SSL (I haven't changed the defaults in wellknown.js--Zoho still has `secureConnection: true`).

**Comment by andris9** [comment]
Upgrade Nodemailer to v0.7.1 (the last version that is compatible with 0.3.28) and try again

**Comment by brentcklein** [comment]
I actually didn't realize my Nodemailer was so out of date until I submitted this issue.  I did just that, and it solved the issue.  Thanks for all your hard work on this!

**Comment by PierreGabioud** [comment]
I'm having the same problem, with nodemailer v2.3.1. Any hints?

**Comment by export-mike** [comment]
@PierreGabioud did you get around this in the end?

**Comment by gvzq** [comment]
The bug still prevails I can't connect using Zoho.

**Comment by export-mike** [comment]
@gvzq I had mail working in the end. 

```js
import nodemailer from 'nodemailer';

const smtpConfig = {
  // host: 'smtp.zoho.com',
  // port: 465,
  // secure: true, // use SSL
  service: 'zoho',
  auth: {
    user: 'donotreply@mydomain.co.uk',
    pass: process.env.SMTP_PASSWORD
  }
};

const transporter = nodemailer.createTransport(smtpConfig);

export default ({to, html, text, subject}) => {
  const mailOptions = {
    from: 'My Domain <donotreply@mydomain.co.uk>',
    to: Array.isArray(to) ? to.join(', ') : to,
    subject,
    text,
    html
  };

  return new Promise((resolve, reject) => {
    transporter.sendMail(mailOptions, (error, info) => {
      if (error) return reject(error);
      return resolve(`Message sent: ${info.response}`);
    });
  });
};
```
