### ISSUE TITLE
I cant get html to work when its a stream

### ISSUE THREAD

**Issue by Neppord** [andris9/Nodemailer#459]
Acording to the [docs](https://github.com/andris9/Nodemailer#e-mail-message-fields)

>  html - The HTML version of the message as an Unicode string, Buffer, Stream or an object {path: '...'}`

The html field could be a stream. I have tried to send a [hyperstream](https://github.com/substack/hyperstream) but it doesn't seam to work. Sending it as a string works how ever.

**Comment by andris9** [comment]
The correct way to use a stream is like this:

```
{
    filename: 'filename.gif',
    content: fs.createReadStream('filename.gif')
}
```
