### ISSUE TITLE
attachment filename should be generated from 'name' parameter of content type

### ISSUE THREAD

**Issue by bradvogel** [andris9/Nodemailer#461]
Currently when I add an attachment to my message in the form:

```
mail.data.attachments.push({
    contentType: 'image/gif; name="lazyhorse.gif"',
    content: '...'
});
```

nodemailer will generate a filename of "attachment-1.bin":

```
Content-Type: image/gif; name=lazyhorse.gif
Content-Disposition: attachment; filename=attachment-1.bin
Content-Transfer-Encoding: base64

...
```

This is unfortunate because some older email clients block attachments solely based on the filename, with "*.bin" being prohibited.

It would be nice if `Compiler.prototype._getAttachments` in nodemailer tried to get the filename from the contentType before falling back to "attachment-1.bin".

**Comment by wearhere** [comment]
:+1:

**Comment by olofster** [comment]
:zap:

**Comment by andris9** [comment]
This is not going to happen, there's already a ton of fiddling around filenames, I do not want to add any more complexity to it. Use the filename option instead of providing it yourself in the content-type header

**Comment by ricardopolo** [comment]
IMHO this sould be re thinked. 

In our scenario where we parse a mail wiht mailparser and then send it using nodemailer, we see lots of files with "attachment-1.bin" name, and it makes the email be alerted as spam
