### ISSUE TITLE
can not send emails

### ISSUE THREAD

**Issue by vishalpachpande** [andris9/Nodemailer#462]
Hi,
I not able to send emails using gmail yahoo hosts in node.js ,
If I am using yahoo host the I am getting below error
{ [Error: Connection timeout] code: 'ETIMEDOUT' }
And 
If I am using gmail host then I am getting below error
{ [Error: Invalid login]
  code: 'EAUTH',
  response: '534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbtbD\n534-5.7.14 VDVBeNvPO-rr4EZxsAhvbhuvleprL8vCox2PA3AI49eRhh-MY_Uqa4KQLwDJN2SY78I00w\n534-5.7.14 ZqPSK4XgIgZU4YWrtfmgRhNoy5lXJ-8EGDDvWOUwGYtGMei0qsIRnq9dcHAjzSuQM639vR\n534-5.7.14 SdIZHfBXk5jhk8cIgozNIMZPxIppSO4ZZcReqFMRn0iAaJP_jC15Lsvfhh4duIy5vRFqI2\n534-5.7.14 8_sHflJ6khXzsoIyfuSTjJZ_8mxc> Please log in via your web browser and\n534-5.7.14 then try again.\n534-5.7.14  Learn more at\n534 5.7.14  https://support.google.com/mail/answer/78754 l1sm18768548pdp.71 - gsmtp',
  responseCode: 534 }

could anyone help me out pls.
Also i want to use third party mail server

**Comment by andris9** [comment]
Gmail thinks you are sending spam and is blocking your connection. Use another provider like SendGrid or Mailgun etc.

**Comment by vishalpachpande** [comment]
Thanks

can you tell me what exactly the use of service in node mailer code?
