### ISSUE TITLE
Unicode characters encoded as HTML entities, breaking iOS preheader text

### ISSUE THREAD

**Issue by wearhere** [andris9/Nodemailer#463]
If I send an email with HTML
```html
<p>Hi Andris 😀</p>
```

at some point, `😀` gets converted to the HTML entity `&#x1F600;`: what is sent is

```html
<p>Hi Andris &#x1F600;</p>
```

But iOS mail will not render HTML entities in [preheaders](https://www.campaignmonitor.com/blog/post/3628/a-practical-guide-to-email-preheaders/):
![napkin 07-14-15 2 21 52 pm](https://cloud.githubusercontent.com/assets/110000/8685473/ad810c9e-2a33-11e5-966d-f563f1fd126a.png)
If I use a [plugin](https://github.com/andris9/Nodemailer#plugin-api) to unconvert the HTML after resolution (back to `<p>Hi Andris 😀</p>`), then the preheader renders the emoji just fine. And, both desktop Gmail and iOS Mail appear able to render Unicode just fine without entity-encoding.

Do you know of any reason not to undo Unicode entity conversion? Why are characters currently converted and where does this conversion take place?

**Comment by andris9** [comment]
Do you use a relay of some kind that modifies messages (SendGrid, mailgun etc.)? If I send a message like this:

```javascript
{
    …
    html: '<p>Hi Andris 😀</p>'
}
```

then the generated rfc822 source is just like expected:

```
Content-Transfer-Encoding: quoted-printable
Date: Wed, 15 Jul 2015 08:41:26 +0000
Message-Id: <1436949687926-9f9909de-26ab3840-404b17d1@kreata.ee>
MIME-Version: 1.0

<p>Hi Andris =F0=9F=98=80</p>
```

As you can see there is no conversion made, the smiley is transmitted as raw bytes, not as an HTML entity.

**Comment by wearhere** [comment]
Thanks for the quick response @andris9, and apologies on my part for improperly diagnosing the bug—the conversion happens on our end _before_ submitting the message to Nodemailer, due to the way that we process HTML for sending. Keep up the good work :)
