### ISSUE TITLE
Bcc doesn't work.

### ISSUE THREAD

**Issue by nsabovic** [andris9/Nodemailer#465]
Setting the bcc field has no effect.

The root cause is buildmail. When using buildmail, if keepBcc is not set in the options, Bcc field will be stripped from the resulting message.

I'm making a pull requests right now.

**Comment by andris9** [comment]
Why do you want to keep bcc in the headers section? Bcc is a property of the smtp envelope not the message itself, otherwise it would make no sense as all recipients would see the bcc addresses

**Comment by sahilsk** [comment]
@andris9 
for me also bcc is not working. I get mail for only email id i put in "to" field.


sendmail tranport
``` js
transporter = nodemailer.createTransport(sendmailTransport({
   					 path: '/usr/sbin/sendmail'
					}));
```
mailoption

``` js
			email_list[0] = "sonukr1@mailinator.com"
			email_list.push("sonukr2@mailinator.com");
			email_list.push("sonukr3@mailinator.com");
			mailOptions = {
			    from: fromMailer,
			    to:  email_list[0] ,
			    cc: 'sonukr.meena@xyz.com',
			    bcc: email_list.slice(1, email_list.length),
			    subject: 'WARNING: Your github account is found with 2FA disabled', 
			    text: mailBody,
			    html: mailBody.replace( new RegExp('\n', 'g'), "<br/>")
			};
			console.log("Dispatching security notice alert to ", mailOptions.bcc);
			transporter.sendMail(mailOptions, function(err, info){
				console.log("Status:  ", info);
				cb(err, null);
			}); 
```

Status body:

``` js
Status:   { envelope: 
   { from: 'github.reporter-noreply@xyz.com',
     to: 
      [ 'sonukr1@mailinator.com',
        'sonukr.meena@xyz.com',
        'sonukr2@mailinator.com',
        'sonukr3@mailinator.com' ] },
  messageId: '1437484238567-41754203-7699c46a-713954b6@xyz.com' }

```

**Comment by sahilsk** [comment]
Oh, i think bcc is working.  And i can see my email id in `cc`. Why i didn't get the mail copy , i wonder?


![image](https://cloud.githubusercontent.com/assets/5857895/8801684/0eb4713a-2fda-11e5-97fd-a66ab46282fc.png)
