### ISSUE TITLE
Is it possible to set base64 encoding on the subject?

### ISSUE THREAD

**Issue by CheeseTheMonkey** [andris9/Nodemailer#468]
sending with:

    transport.sendMail(
    {
      sender: config.sender,
      to: to,
      subject: subject,
      html: body,
      encoding: 'base64'
    });

I receive the email content as expected, but with a japanese subject I'm missing the final 2 characters in some email clients (mainly outlook). From the message headers:

    Subject: =?UTF-8?Q?=E3=82=AF=E3=83=A9=E3=82=A6=E3=83=89?=
    =?UTF-8?Q?=E3=82=B9=E3=83=88=E3=83=AC=E3=83=BC?=
    =?UTF-8?Q?=E3=82=B8=E3=82=B9=E3=82=AD=E3=83=A3?=
    =?UTF-8?Q?=E3=83=B3_=E3=82=BB=E3=82=AD=E3=83=A5?=
    =?UTF-8?Q?=E3=83=AA=E3=83=86=E3=82=A3=E3=83=AC?=
    =?UTF-8?Q?=E3=83=9D=E3=83=BC=E3=83=88?=

Japanese email has always been tricky, however most suggestions include using =?iso-2201-j?B? or even just base64 encoding with UTF-8 to make this work.

As such, is it possible to encode the subject in this way?

**Comment by andris9** [comment]
I didn't really get it. Is Nodemailer sending out subjects without the 2 final characters or is the subject itself fine but the clients are not displaying the last characters?

**Comment by CheeseTheMonkey** [comment]
The subject appears fine in a number of clients, but outlook and others are notoriously bad at encoded subject lines. For now though we've found a workaround:

    transport.sendMail(
    {
    sender: config.sender,
    to: to,
    subject: libmime.encodeWords(subject, 'B', 52),
    html: body,
    encoding: 'base64'
    });

as encodeWords won't re-encode already encoded strings.

Thanks for the quick reply
