### ISSUE TITLE
Node mailer sends some junk characters in a html email template

### ISSUE THREAD

**Issue by jayabhar** [andris9/Nodemailer#471]
Greetings!!

I am facing some issues with node mailer . I have a HTML template which I am sending it to node mailer. After receiving the mail, it shows some junk character (!) which is placed at a random location. In documentation I saw that node mailer has a default encoding as UTF-8. I tried with ASCII and UTF-16 too, but no luck. 
Can you please help me with this? 

Thanks,
Jay

**Comment by andris9** [comment]
If you still have this issue, then create a self contained example script that has this behavior and that can be used to verify this bug
