### ISSUE TITLE
Send headers and manipulate it in html

### ISSUE THREAD

**Issue by denebchorny** [andris9/Nodemailer#472]
HI Sir,

Sorry for bother you and sorry for my ignorance but sometimes the obvious will be ignored.

I'm trying to send parameters into the header and trying to receive it and manipulate it in the html but I didn't find yet the way to do it.

<strong>I send the header as well:</strong>

app.models.Email.send({
    to: 'mailname@mail.com',
    from: systemEmail,
    subject: 'Password reset',
    text: password,
    html: file,
    headers: {"X-password": password}
  }, function(err) {
    if (err) throw err;
    console.log('> email sent successfully', file);
  });

<strong>This is a small piece of the HTML as example, where "X-password" is the Key-Name of a param in the header:</strong>

```<h2 style="margin: 0;padding: 0;font-size: 28px;font-family: 'Avenir Next', &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;line-height: 1.25;margin-bottom: 20px;">Hi X-password,</h2>```

<strong>And this is how it shows in the mail:</strong>

![problem](https://cloud.githubusercontent.com/assets/13120695/9087650/c98e8aaa-3b55-11e5-8700-1642bb6f30dc.png)

<h3><strong>Please, save me for GOD SAKE T.T</strong></h3>

**Comment by andris9** [comment]
Does not seem to be Nodemailer related. Check the docs of `app.models.Email.send`
