### ISSUE TITLE
{ [Error: Connection timeout] code: 'ETIMEDOUT' }  && TypeError: Cannot read property 'response' of undefined

### ISSUE THREAD

**Issue by HelloKevinTian** [andris9/Nodemailer#473]
I got the error with sending an email with nodemailer(version: 1.4.0).

        var transporter = nodemailer.createTransport({
			service: 'Gmail',
			auth: {
				user: 'test@gmail.com',
				pass: 1234
			}
		});

		// setup e-mail data with unicode symbols
		var mailOptions = {
			from: 'test@gmail.com',
			to: 'test1@gmail.com',
			subject: 'Hello ✔',
			text: 'Hello world ✔',
			html: '<b>Hello world ✔</b>'
		};

		// send mail with defined transport object
		transporter.sendMail(mailOptions, function(err, info) {
			if (err) {
				logger.error(err);
			}
			logger.info('Message sent: ' + info.response);
		});

**Comment by andris9** [comment]
ETIMEDOUT is usually related to firewall blocking imap.gmail.com ports 465 or 587. The TypeError happens because you try to use `info` object while an error happened. If the `err` object is set, then `info` is not.

**Comment by HelloKevinTian** [comment]
When I try to use the low version 0.7,the error disappeared
