### ISSUE TITLE
Sendgrid - per connection limit

### ISSUE THREAD

**Issue by ranode** [andris9/Nodemailer#475]
Hi,

Sendgrid documentation says : With SMTP, 100 messages can be sent with each connection.

Does it mean that when use createTransport, I can send only 100 messages per transport? Or Can I use the transport object to send mail as much as you like like the documentation says.

**Comment by andris9** [comment]
This depends on the transport method. If you ise the default SMTP transport, then a new tcp connection is created for every message and the limit does not apply (only one message is sent by one connection). If you use [smtp-pool transport](https://github.com/andris9/nodemailer-smtp-pool) where connections are reused, then you should set the `maxMessages` option for the transport to 100 or lower.

**Comment by ranode** [comment]
Great! Thanks so much for your response...
