### ISSUE TITLE
Nodemailer not sending occasional emails

### ISSUE THREAD

**Issue by andyrichard** [andris9/Nodemailer#476]
I am using node mailer for a project and most of the time it is working great.
On occasion it will not send an email and does not return any error message or clues as to what is going wrong.
Has anyone else had this problem or similar?

**Comment by andris9** [comment]
E-mails are not 100% percent reliable, the issue might be related to anything. If you ever find out what is actually causing this and Nodemailer is doing something wrongly then create a new issue
