### ISSUE TITLE
Inline CSS Disappearing

### ISSUE THREAD

**Issue by eruby94** [andris9/Nodemailer#479]
I have just begun to use this to send emails upon a form submission, and I am attempting to send an html body with background-color and color stylings, etc..

When I send the email, it appears without the background color and color styling, but leaves present the display stylings. I am confused as to where in the process this is getting screwy, but something is definitely not working.

**Comment by andris9** [comment]
Nodemailer just passes on the HTML you have defined and does not modify it in any way. Designing e-mail templates is a science in itself, for example see this article for tips: http://www.sitepoint.com/how-to-code-html-email-newsletters/
