### ISSUE TITLE
Blob or Array Buffers attachments

### ISSUE THREAD

**Issue by Siafu** [andris9/Nodemailer#480]
How would I attach a blob or array buffer ? The data is coming back from jsReports server as an array buffer. Do have have to save to disk before emailing as an attachment ?

**Comment by andris9** [comment]
Are you really using ArrayBuffers in Node.js? Nodemailer supports Buffer objects even though ArrayBuffers might work as well, I haven't tested it.

**Comment by Siafu** [comment]
I got it working converted it to base64

**Comment by johnEthicalTechnology** [comment]
@Siafu thank-you for this! It saved me a lot potential hassle.
