### ISSUE TITLE
Send 100 mails one at a time or bulk

### ISSUE THREAD

**Issue by ju4nkA** [andris9/Nodemailer#482]
I want to send 100 mails using nodemailer-smtp-pool. In the "to" field the receivers just have to see his email address. This just can do it sending one at a time mail? If so, it's correct to leave the sender waiting until all mails are sent or there is another way to do it?

Thanks.

**Comment by andris9** [comment]
You need to send one email per recipient, for 100 messages you can use a `for` loop for this
