### ISSUE TITLE
chinese attachment name is not right 

### ISSUE THREAD

**Issue by iamlaobie** [andris9/Nodemailer#484]
when i send a mail with a chinese name attachment,the chinese name look like this "tcmime.2078.2333.2494.bin" in some email server, e.g mail.qq.com,but it's ok in mail.163.com

**Comment by iamlaobie** [comment]
the problem as this:
https://github.com/andris9/Nodemailer/issues/416

**Comment by andris9** [comment]
This has been updated in v1.6.0. Nodemailer now uses QQ compatible filename headers
