### ISSUE TITLE
High Priority boolean

### ISSUE THREAD

**Issue by alexnaspo** [andris9/Nodemailer#485]
Is it possible to send an email has high priority? If not, this would be a nice feature.

Thanks!

**Comment by ergdev** [comment]
+1
This would be a great feature

**Comment by andris9** [comment]
I'm not sure if this should be added or not. In the meantime you can set this by using custom headers:

```
mailOptions = {
    from: ...
    ...
    headers: {
        'X-Priority': '1 (Highest)',
        'X-MSMail-Priority': 'High',
        'Importance': 'High'
    }
}
```

**Comment by andris9** [comment]
Added `priority` option ("high", "normal", "low") with 32b0dc07e7616c506527f0c8be7dc0689f5bf0c6. Will be available whenever I make a new release.
