### ISSUE TITLE
Not able to send mail from Node Mailer 

### ISSUE THREAD

**Issue by RanaAnkit** [andris9/Nodemailer#486]
I am trying to send mail through nodemailer in my node js application. when i send mail via gmail services it works fine but when i use some smtp server to send message some error occured "dh key is too small". interesting thing is when i send mail using same configuration from windows server mail sending is working flawlessly. but when i try to send via ubuntu using same configuration same message occur "dh key is too small". here is my configuration

var smtpTransport = nodemailer.createTransport({
     host: "mail.XXXX.com", // hostname
      secureConnection: false, // use SSL
     port:"XX",
    auth: {
        user: "XXX@XXX.com",
        pass: "XXXX"
    }
});

The same code is working when I am using windows machine but not on Ubuntu

**Comment by andris9** [comment]
This is probably an issue with openssl. You should try to upgrade Node.js on your ubuntu box to get the latest openssl bindings.
