### ISSUE TITLE
Report back failed deliveries?

### ISSUE THREAD

**Issue by binarykitchen** [andris9/Nodemailer#487]
Sometimes my users enter invalid email addresses. When these emails are sent, I receive bounced error messages.

Would be great if nodemailer can scan for these in the mail logs and return errors instead. So that I can process and show users warnings.

Here an example for Postfix mail logs:

```
Sep  8 15:15:15 blahblah postfix/smtp[29792]: 4568B22190: to=<james@net.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=15, delays=10/0.01/0/4.9, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as D67D5221F8)

Sep  8 15:15:18 blahblah postfix/smtp[29796]: D67D5221F8: to=<james@net.com>, relay=none, delay=1.9, delays=1.7/0.02/0.18/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=net.com type=AAAA: Host found but no data record of requested type)
```

The last line is an indication that delivery has failed and could be returned as an error.

I know this is a bigger request and causes some delay in the callback but would be an awesome feature!

**Comment by andris9** [comment]
Thats kind of out of scope for Nodemailer. The "standard" bounce handling is to use VERP, eg. to use a custom FROM address for the SMTP envelope and then listen for messages for this address – if anything is received then the message has bounced. 

You could set up a [smtp-server](https://github.com/andris9/smtp-server) for a custom MX domain, eg. *bounces.mydomain.com* and when using Nodemailer use this domain for the envelope

```
mailOptions = {
    from: 'sender@mydomain.com',
    to: 'receiver@example.com',
    messageId: 'abcdef',
    envelope: {
        from: 'abcdef+receiver+example.com@bounces.mydomain.com',
        to: ['receiver@example.com']
    }
}
```

The smtp-server would listen for incoming messages, accept everything but storing nothing. Once a message is received, it checks the TO address and if the address is *abcdef+receiver+example.com@bounces.mydomain.com* then it can emit an event that a message with message-id `'abcdef'` to *receiver@example.com* was bounced. You should also look into the message body to see the reason but this is probably quite difficult as every server software uses a different format for bounce messages.

Anyway, this feature is out of scope for Nodemailer and will not be added

**Comment by binarykitchen** [comment]
@andris9 great suggestion, will try this - many thanks!

but does it have to be a separate domain like `bounces.mydomain.com`? why can't it just be `noreply@videomail.io`? And the smtp-server passes through any emails except the noreply one.

**Comment by andris9** [comment]
Yeah, the domain itself doesn't matter as long as you have some kind of mechanism to differentiate between normal emails and bounce messages.

**Comment by binarykitchen** [comment]
@andris9 great - how can I pass through all the other emails except one? probably I should ask this in https://github.com/andris9/smtp-server but since you are the same maintainer, let me ask all the questions here in the same thread if you do not mind?

**Comment by andris9** [comment]
Use the `onRcptTo` callback to check if the recipient address looks like a bounce and if so then treat the message as bounce message, eg. something like this:

```javascript
var server = new SMTPServer({
    onRcptTo: function(address, session, callback) {
        // assuming bounce addresses are bounce-[:id]@yourdomain
        var bounce = address.address.match(/^bounce\-([^@]+)@/);
        if (bounce) {
            session.isBounce = true;
            console.log('Bounced message with id %s', bounce[1]);
        }
        return callback(); // Accept the address
    },
    onData: function(stream, session, callback) {
        if (session.isBounce) {
            // ignore message data
            stream.on('data', function() {});
            stream.on('end', function() {});
        } else {
            // handle regular message
            …
        }
    }
});
```

**Comment by binarykitchen** [comment]
Ah, wonderful, this is just perfect, what I need.

One more problem: I already run Postfix on localhost. How can I circumvent the `SMTP server error: Error: listen EACCES 127.0.0.1:25` problem?

If Postfix is configured to run on port 25, how should I configure the port number for the SMTPServer instance then?

**Comment by andris9** [comment]
You can't run several applications on the same port and for a MX you need to use port 25. You should either run the node smtp or Postfix but not both or alternatively run Postfix in one machine and the node based server on another (that's why I suggested using separate domains for bounces)

**Comment by binarykitchen** [comment]
Right, I see. Hmmm, this makes it complicated as I only have one virtual server available and can't afford a second one right now.

Can I configure Postfix to redirect emails of one specific address to a different port on localhost, i.E. to the SMTPServer instance?

**Comment by andris9** [comment]
No idea. Probably you can but I don't know how, check the Postfix docs

**Comment by binarykitchen** [comment]
Okay, I ll give these instructions a try
http://serverfault.com/questions/67134/proxy-mail-to-different-smtp-server-with-postfix

Many thanks again - I am doing all that for www.videomail.io where Deaf people can send out emails in Sign Language.

**Comment by kehers** [comment]
@andris9 How does `envelop.from` relate to the `dsn.recipient`? The [doc](https://nodemailer.com/smtp/dsn/) says "recipient – is the email address the DSN should be sent (ORCPT)". I have actually tried tracking status notification with this but I get noting.

Also, I have noticed that in most cases, if the `envelop.from` is different from actual `from` the mail will not be sent. (If you are setting up your own mail server and sending from it though, there are workarounds). @binarykitchen what worked for you?

**Comment by DRocksCoding** [comment]
I also wonder how the Dsn recipient should work. Cause no matter what email I put there it's only the from email address gets the notification. I'd like to forward failures to a different address than the from address.

**Comment by haydanu** [comment]
> I also wonder how the Dsn recipient should work. Cause no matter what email I put there it's only the from email address that receives the notification. I'd like to forward failures to a different address than the from address.

Hay @DRocksCoding, have u resolved this?

**Comment by alex-drocks** [comment]
@haydanu No. My test case is very specific though and havent tried other scenarios. 
I was trying to use MY email server to let users send emails to THEIR customers. So I needed to return delivery mail errors to THEIR email adress and not my email server.
