### ISSUE TITLE
Nodemailer without Gmail

### ISSUE THREAD

**Issue by aralroca** [andris9/Nodemailer#493]
All the **Nodemailer** examples that I found are for Gmail... 

    var transporter = nodemailer.createTransport({
        service: 'Gmail',
        auth: {
            user: 'gmail.user@gmail.com',
            pass: 'userpass'
        }
    });

How can I put another service? In special I bought a email domain in [**ovh**][2] (**SSL0.OVH.NET**) and I interested to configure this email account.

I tried but I don't found the way to get this...

*Thank you!*

  [1]: https://github.com/andris9/Nodemailer
  [2]: https://www.ovh.co.uk

**Comment by andris9** [comment]
You can find the full options [here](https://github.com/andris9/nodemailer-smtp-transport#usage).

Using

    service: 'gmail'

Is the same as using

    host: 'smtp.gmail.com',
    port: 465,
    secure: true // keep false if using port 587 or STARTTLS

**Comment by aralroca** [comment]
Thank you!!!
