### ISSUE TITLE
Content-Type not being set to multipart/mixed & boundary not being set

### ISSUE THREAD

**Issue by coreygeesey** [andris9/Nodemailer#495]
I'm having an issue after updating from nodemailer 0.3.37 to 1.5.0. I updated all of the api calls and such to emails are being sent. However, when I include attachments, it's like the header isn't being set as multipart/mixed and the boundary isn't being set, as what I end up getting in my inbox is as follows:

```
------sinikael-?=_1-Fri Oct 02 2015 13:07:29 GMT-0500 (CDT)0.3026096122339368
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

This is a test from your donkey on wrench-1-13 with attachment
------sinikael-?=_1-Fri Oct 02 2015 13:07:29 GMT-0500 (CDT)0.3026096122339368
Content-Type: audio/wav
Content-Disposition: attachment; filename=Donkey.wav
Content-Transfer-Encoding: base64

UklGRqbqCgBXQVZFZm10IBIAAAABAAEAESsAACJWAAACABAAAABkYXRhgOoKAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
... (continued)
```

The code that is being used for the transporter:
```javascript
var init = function init () {
    log.debug("Action Init Function");
    if ((typeof (c.SMTP_SERV) === "undefined" && c.SMTP_SERV === null) || (c.SMTP_SERV === '')) {
        // Use sendmail to send emails
        transporter = nodemailer.createTransport(sendmailTransport({
            path:  '/usr/sbin/sendmail'
        }));
        log.debug("Using sendmail to send email.");
    } else {
        // use remote smtp server to send emails
        if (c.SMTP_PORT) {
            this.smtp_port = c.SMTP_PORT;
        } else {
            this.smtp_port = 25;
        }

        //one time action to set up SMTP information for nodemailer
        transporter = nodemailer.createTransport(smtpTransport({
            host: c.SMTP_SERV,
            port: this.smtp_port,
            use_authentication: true,
            auth: {
                user: c.SMTP_USER,
                pass: c.SMTP_PASS
            }
        }));

        log.debug("Using SMTP server [" + c.SMTP_SERV + "] at port [" + this.smtp_port + "] to send email.");
    }
};
```

and for sending the email:
```
                log.debug("Sending email with attachment [" + fullPath + "]");
                transporter.sendMail(
                    {
                        from: sender,
                        to: toAddress,
                        subject: subject,
                        text: body,
                        attachments: [ {
                                path: fullPath
                            }
                        ]
                    }, function (error, response) {
                        if (error) {
                            log.error('Email send with attachment failure: ' + error);
                        }
                    }
                );
```

**Comment by andris9** [comment]
There problem in your case seems to be that Date.now() is producing weird values. Do you use some kind of modules that modify the Date object?

Anyway, the boundary includes the value of `Date.now().toString()` as one component. Normally it would be something like "1443815228744" but your boundaries use "Fri Oct 02 2015 13:07:29 GMT-0500 (CDT)" (seems like the value for `Date().toString()`) instead of the expected numeric value.

Anyway, you should check if `Date.now()` returns a number. Alternatively you could define the random part of the boundary yourself with argument `baseBoundary`

```javascript
{
    from: sender,
    to: toAddress,
    subject: subject,
    text: body,
    attachments: [ {
            path: fullPath
        }
    ],
    baseBoundary: "some-random-string-without-spaces"
}
```

**Comment by xuakson** [comment]
Sir i was able to do this but still maintains NmP and Part_1, is there anyway i can change that too?

**Comment by xuakson** [comment]
> There problem in your case seems to be that Date.now() is producing weird values. Do you use some kind of modules that modify the Date object?
> 
> Anyway, the boundary includes the value of `Date.now().toString()` as one component. Normally it would be something like "1443815228744" but your boundaries use "Fri Oct 02 2015 13:07:29 GMT-0500 (CDT)" (seems like the value for `Date().toString()`) instead of the expected numeric value.
> 
> Anyway, you should check if `Date.now()` returns a number. Alternatively you could define the random part of the boundary yourself with argument `baseBoundary`
> 
> ```js
> {
>     from: sender,
>     to: toAddress,
>     subject: subject,
>     text: body,
>     attachments: [ {
>             path: fullPath
>         }
>     ],
>     baseBoundary: "some-random-string-without-spaces"
> }
> ```

Sir i was able to do this but still maintains NmP and Part_1, is there anyway i can change that too?
