### ISSUE TITLE
Getting error in in amazon ses service

### ISSUE THREAD

**Issue by Ashesh007** [andris9/Nodemailer#497]
{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:email.us-west-2.amazonaws.com
x-amz-content-sha256:37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3
x-amz-date:20151007T094246Z

host;x-amz-content-sha256;x-amz-date
37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20151007T094246Z
20151007/us-west-2/ses/aws4_request
d3f4ff7ef8b0ce8edf79fa199ff3fe9dd119e1c1391824983cce554f5e375a14'
]
  message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'POST\n/\n\nhost:email.us-west-2.amazonaws.com\nx-amz-content-sha256:37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3\nx-amz-date:20151007T094246Z\n\nhost;x-amz-content-sha256;x-amz-date\n37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3\'\n\nThe String-to-Sign should have been\n\'AWS4-HMAC-SHA256\n20151007T094246Z\n20151007/us-west-2/ses/aws4_request\nd3f4ff7ef8b0ce8edf79fa199ff3fe9dd119e1c1391824983cce554f5e375a14\'\n',
  code: 'SignatureDoesNotMatch',
  time: Wed Oct 07 2015 15:12:47 GMT+0530 (IST),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }

Getting above error while using amazon sns service for mailing,
and while this secretKey and accestokenkey used in PHP its working. then what should i have to do??

**Comment by andris9** [comment]
Are you using a correct region? Nodemailer defaults to *us-east-1*

**Comment by Ashesh007** [comment]
yes it's same, this will work using my PHP script.......... but not working in nodejs script...

**Comment by andris9** [comment]
In case of SES; Nodemailer uses [aws-sdk](https://www.npmjs.com/package/aws-sdk) under the hood and does not generate any signatures etc. by itself. The arguments passed to aws-sdk are `accessKeyId`, `secretAccessKey`, `sessionToken` and `region` (defaults to "us-east-1"), so if the signature does not match, then you should look into what aws-sdk does with your data. Anyway it is out of scope for Nodemailer.

**Comment by Ashesh007** [comment]
thank u :)

**Comment by wtfiwtz** [comment]
See also https://github.com/andris9/nodemailer-ses-transport/issues/11 - recommends checking access permissions in IAM
