### ISSUE TITLE
dns failure

### ISSUE THREAD

**Issue by pacmac** [andris9/Nodemailer#498]
What does nodemailer direct method use for it's dns lookups as it is not sending emails with DNS error, however if I perform a dnslookup at the command line using nslookup then the recipient domain can be resolved no problem:

	Queued message #1 from noreply@xxx.com, to xxx@xxx.com
	xxx-dev-0 { message: 'Message Queued',
	  messageId: '2d7676e4f3042b5e40fb475e523351@xxx-dev',
	  statusHandler: { domain: null, _events: {}, _maxListeners: undefined } }
	xxx-dev-0 Retrieved message #1 from the queue, resolving xxx.com
	xxx-dev-0 Resolving xxx.com for #1 failed
	xxx-dev-0 { [Error: queryMx ENODATA xxx.com]
	  code: 'ENODATA',
	  errno: 'ENODATA',
	  syscall: 'queryMx',
	  hostname: 'xxx.com' }

**Comment by andris9** [comment]
Do you try to resolve MX or A/AAAA records with nslookup?

**Comment by pacmac** [comment]
Thanks for the very quick reply, yes I did, it was successful:

	nslookup xxx.com. -query=mx
	Server:		192.168.42.20
	Address:	192.168.42.20#53
	
	Name:	xxx.com
	Address: 192.168.42.20

**Comment by andris9** [comment]
Do you see the same results with dig?

```
dig MX xxx.com
```

Nodemailer direct transport uses Node.js [dns library](https://nodejs.org/api/dns.html) to resolve the addresses

**Comment by pacmac** [comment]
Yes, the lookup is OK, but I think this is related to the fact that the destination server is on the same subnet (LAN) and the dns lookup is getting the public address rather than the private address, I can work around this.

Thanks for you quick response, I will close the issue now.

**Comment by abjagtap** [comment]
@pacmac what is work around?
