### ISSUE TITLE
Downgrade  to 0.7.1

### ISSUE THREAD

**Issue by lrAlval** [andris9/Nodemailer#500]
Hi, when trying to use XOAuth2 with Gmail Account ,throws this message
[Error: Unsupported configuration, downgrade Nodemailer to v0.7.1 or see the migration guide https://github.com/andris9/Nodemailer#migration-guide]
and cant find how to downgrade or the url is invalid .

Thanks in Advance

**Comment by andris9** [comment]
Sorry, the URL is expired and I haven't been able to get it back up. Here's the docs for using XOAuth2 with the latest version of Nodemailer: https://github.com/andris9/nodemailer-smtp-transport#authentication
