### ISSUE TITLE
Blocked by Spamhaus

### ISSUE THREAD

**Issue by diginfo** [andris9/Nodemailer#502]
Hi;

I am using the direct method, however the ip has now been blocked by spamhaus.

This machine has a static ip address, a domain name and a reverse dns setup.

It appears that the HELO uses localhost instead of the domain name, how can I set the domain name such that HELLO includes it instead of localhost ?

	IP Address xx.xx.xx.xx is listed in the CBL. It shows signs of being infected with a spam sending trojan, malicious link or some other form of botnet.
	
	It was last detected at 2015-10-20 00:00 GMT (+/- 30 minutes), approximately 3 hours ago.
	
	The listing of this IP is because it HELOs as 127.0.0.1. Not only is this a violation of RFC2821/5321 section 4.1.1.1, it's even more frequently a sign of infection.
	
	In all probability this IP address is a NAT gateway, and the machine at 127.0.0.1 in your local LAN is either infected, or if it's a server, badly misconfigured.

**Comment by andris9** [comment]
Direct transport uses `localhost` if it fails to detect the current hostname of the server. You can use the `name` property to override it

```javascript
var nodemailer = require('nodemailer');
var directTransport = require('nodemailer-direct-transport');
var transporter = nodemailer.createTransport(directTransport({
    name: 'my-host.example.com'
}));
```

**Comment by scagood** [comment]
It would be great if you could include something about this in your examples or equivalent as I've been got by this problem too and it took a lot longer than I'd have liked to find this as the internet didn't seem to help much :) 

Thanks sca
