### ISSUE TITLE
No error if server goes down.

### ISSUE THREAD

**Issue by medokin** [andris9/Nodemailer#505]
I tried to send a mail to my custom smtp-server using smtp transporter.

There was an error while processing the incoming email on my server and it shut down. I expected a error message from nodemailer, but instead the callback never fired.

``` js
var transporter = nodemailer.createTransport(
  {
    host: 'not.reliable.server',
    port: 25,
    auth: {
      user: 'test',
      pass: 'test'
    }
}

console.log('Sending Email...')
tansporter.sendMail(mailOptions, function(error, info) {
 console.log('nobody calls me... :('
});
```

Result
``` bash
C:\dev> node index
C:\dev> "Sending Email..."
C:\dev>

**Comment by andris9** [comment]
This is most probably fixed in v1.9.0. Could you try again?
