### ISSUE TITLE
Google is telling me not to use your app

### ISSUE THREAD

**Issue by zwhitchcox** [andris9/Nodemailer#507]
Just tried to use nodemailer with gmail, and it's saying you guys aren't a secure app.
```
Hi
Someone just tried to sign in to your Google Account from an app that doesn't meet modern security standards.
Details:
Saturday, October 31, 2015 4:56 PM (Eastern Daylight Time)
New York, NY, USA*
We strongly recommend that you use a secure app, like Gmail, to access your account. All apps made by Google meet these security standards. Using a less secure app, on the other hand, could leave your account vulnerable. Learn more.

Google stopped this sign-in attempt, but you should review your recently used devices:

REVIEW YOUR DEVICES NOW
```

**Comment by andris9** [comment]
There is nothing wrong with Nodemailer in this regard. Google enforces all new Gmail users to use only OAuh2 based authentication in apps. You can either allow so called "less secure apps" by updating your Google [account settings](https://support.google.com/accounts/answer/6010255?hl=en) or switch from password based authentication to OAuth2 based authentication in Nodemailer, see details [here](https://github.com/andris9/nodemailer-smtp-transport#authentication).
