### ISSUE TITLE
550 invalid DNS MX or A/AAAA resource record

### ISSUE THREAD

**Issue by exor1** [andris9/Nodemailer#510]
Hi,

i use nodemailer V1.8.2 und nodemailer-smtp-transport.

var transp = mail.createTransport(smtpTransport({
        host: 'smtp.1und1.de',
        port: 587,
        secureConnection: false,
        tls:{
            ciphers:'SSLv3' },
        greetingTimeout: '9000', 
auth: {
        user: 'ez3@online.de',
        pass: 'krk12345'
    }
}));

if i try to send  e-mail i receive following error :
 [Error: Mail command failed]
  code: 'EENVELOPE',
  response: '550-Requested action not taken: mailbox unavailable\n550 invalid DNS MX or A/AAAA        resource record',
  responseCode: 550 }

I change to nodemailer v0.7.1 without nodemailer-smtp-transport :

 var transp = mail.createTransport('smtp',
	  {
                 service: '1und1',
		host: 'smtp.1und1.de',		
		tls: {rejectUnauthorized: false}, 
                port: 587,          	 
         auth: {
        user: 'ez3@online.de',
        pass: 'krk12345'
    }
}));

I get the same error.

If i change the host: 'smtp.1und1.de'
to host: smtp.gmail.com it works, but i need host: smtp.1umd1.de

Thanks.  
Joachim

**Comment by andris9** [comment]
This error means that your smtp server refuses to send mail to specified recipient because there is an issue with the domain name of the recipients address

**Comment by exor1** [comment]
Hi,

thank for fast reply.
I can send from other mail programms e.g. gmail,  to adress ez3@online.de, but not with nodmailer.

**Comment by andris9** [comment]
Could you show your `transp .sendMail` mail options as well? Are you trying to send mail to yourself then? You authenticate as ez3@online.de and want to send to ez3@online.de?

**Comment by exor1** [comment]
Hi,
transp.sendMail
{         
	 from: "emloc@webserver.de",
	 to:   'seitz@seitz-electronic.de', // my mail adress text[2],
         subject: "Webserver V1.0",
         text: data2[2], //"Message from EZ", 
	 body:'',		  
	 attachments : [
	  {'filename': 'EZ Message.txt','contents': data}]
		 
       },
       function(err,response)
	   {
          if(err){
            console.log(err);
       }
       console.log(response);
     });
 });

**Comment by exor1** [comment]
Hi,
your ask : You authenticate as ez3@online.de and want to send to ez3@online.de?

Yes, i want to send an e-mail with nodemailer via SMTP to my address: ez3@online.de, or other valid address : seitz@seitz-electronic.de
Host SMTP.1und1.de, Port: 587

**Comment by andris9** [comment]
In your example you are trying to send mail from emloc@webserver.de but webserver.de is not a valid mail host. Gmail always overrides the from address to match the authenticated user, so it does not validate from addresses, 1und1 probably does.

**Comment by exor1** [comment]
you are right,
emloc@webserver.de is not a valid address, is only text in the mail header.
If i change address to seitz@seitz-electronic.de, i get the same error :
if i try to send  e-mail i receive following error :
 [Error: Mail command failed]
  code: 'EENVELOPE',
  response: '550-Requested action not taken: mailbox unavailable\n550 invalid DNS MX or A/AAAA        resource record',
  responseCode: 550 }

If i change to host:smtp.gmail.com, it works : 

	var transp = mail.createTransport(smtpTransport({
        host: 'smtp.gmail.com',
        port: 587,
		secureConnection: false,
		//ignoreTLS: true,
		 tls:{
            ciphers:'SSLv3' },
		//connectionTimeout: '9000',
		greetingTimeout: '9000',
    auth: {
        user: 'ws.ez2.001@gmail.com',
        pass: 'krk12345'
    }
}));

i get following mesage :

{ accepted: [ 'seitz@seitz-electronic.de' ],
  rejected: [],
  response: '250 2.0.0 OK 1446713388 t2sm7220794wme.0 - gsmtp',
  envelope:
   { from: 'emloc@webserver.de',
     to: [ 'seitz@seitz-electronic.de' ] },
  messageId: '1446720351839-25f63b79-baacfb04-5928fa4b@webserver.de' }

**Comment by andris9** [comment]
`from:` address is not just a line in the header, it is also used as the MAIL FROM address for the SMTP envelope. If it is not a valid value, then some SMTP servers might not accept it. Use a valid `from` address or override it with the `envelope` option described [here](https://github.com/andris9/Nodemailer#smtp-envelope). Gmail works because gmail does not look at the from values, it always uses authenticated user's e-mail address and skips the value provided by the client.

**Comment by exor1** [comment]
I have change the  address in  from: emloc@webserver.de to my valid address seitz@seitz-electronic.de, but i have the same error with host: smtp1und1.de.

**Comment by exor1** [comment]
Thank you  for your good e-mial support .
Could you  tell me diference between Nodemailer V0.1.2 an Nodemailer V1.8 + smtp-transport  and nodemailer wellknown ?
Thanks.

**Comment by Nonemoticoner** [comment]
I have the same problem right now and I'm using 1and1 services as well. @exor1 did you find the solution?

**Comment by Vizzard** [comment]
Hi, verify that domain you want to send mail to does not have CNAME in MX record. It's not according to RFC and 1and1 does not like that: 
http://tools.ietf.org/html/rfc2181#section-10.3
They fail to deliver with exact error you wrote.
Google probably tolerate such DNS configuration and successfully delivers. 

Example thread: http://www.iredmail.org/forum/topic8938-iredmail-support-550requested-action-not-taken-mailbox-unavailable-550-invalid-dns.html

**Comment by exor1** [comment]
sorry for the late reply, but I was sick.
The sender in the from line: "EmLOC Web server V1.0" was wrong, it must be a valid address as
be 'ws@krk.de': when Auth: {user. In Gmail, this error will be automatically intercepted.
1und1 is a provider from Germany, are also from Germany?
