### ISSUE TITLE
Documentation of how to create Promise wrapper for transporter.sendMail

### ISSUE THREAD

**Issue by rightaway** [andris9/Nodemailer#512]
In https://github.com/andris9/Nodemailer/issues/294 it says that Promises aren't supported, but since JS is adopting Promises more and more, and Babel already allows for the use of async/await today, it would be great to be able to use nodemailer with async/await. This requires creating a Promise wrapper, as suggested in https://github.com/andris9/Nodemailer/issues/294#issuecomment-49525156.

I can't figure out how to create this wrapper, either using the thenify or thenify-all library, or a manual wrapper. At https://www.npmjs.com/package/thenify they give an example of how to 'thenify' a function, but that's a standalone function. I'd like to know how to 'thenify' a method, specifically the `sendMail` method of the `transporter` object.

Of course it would be ideal if nodemailer supported this out of the box, since as in #294 there's clearly a lot of support and interest in this. But if that won't happen, it would be great if there were a small snippet of code in the documentation showing how people who are interested could create such a wrapper for the `sendMail` function.

**Comment by Slayer95** [comment]
See e.g. https://www.npmjs.com/package/es6-promisify

**Comment by andris9** [comment]
Added a Promise wrapper with b88e7a655e609b0580fff5ec861e6f247755fda1 (v1.9.0). If callback is not defined for `sendMail` then the method returns a native Promise object instead

```javascript
transport.sendMail(options).then(function(info){
    console.log(info);
}).catch(function(err){
    console.log(err);
});
```

**Comment by luileito** [comment]
Please see also https://github.com/nodemailer/nodemailer/issues/294#issuecomment-203876572
