### ISSUE TITLE
Allow configuring a default 'from' address

### ISSUE THREAD

**Issue by rightaway** [andris9/Nodemailer#513]
Since most messages from an application would come from the same `from` email address, it would be nice if it were possible to configure a default from address (perhaps on the transport's option object) that would be used if the mail message doesn't include a from address in its configuration object. Would help make the mail-sending code throughout the application slightly tidier and less repetitive.

**Comment by andris9** [comment]
Good idea. I added a second argument to `createTransport` that defines default values for `sendMail`. This feature will be available with the next release.

```javascript
var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'sender@gmail.com',
        pass: 'password'
    }
}, {
    // default values for sendMail method
    from: 'sender@address',
    headers: {
        'My-Awesome-Header': '123'
    }
});
```
