### ISSUE TITLE
Html not being rendered correctly by email clients

### ISSUE THREAD

**Issue by Alanz2223** [andris9/Nodemailer#517]
I am trying to send simple html emails but no matter how basic the html, they are not being rendered. I have tried Gmail, and Outlook. I get very fancy campaign emails and they render just fine within these clients. I tried to compare the meta of their emails to mine and found that the MIME type is different. Theirs is multipart/alternative and mine is text/html. Upon googling the first type I found that these are used for attaching documents and such but those campaign emails do not have any other attachment. Could that be a way of tricking the email client into properly rendering the html? Anyways I style all elements inline and not even something as simple as a div works.
```
var mes = {
   to:...
  ......
   html : '<div style="background:#000">'+
'hi there'+
'</div>'
}
```

**Comment by andris9** [comment]
Nodemailer does not modify HTML content in any way, so if the e-mail clients to not display the message as intended, check your HTML. I suggest you to read this tutorial about creating HTML emails: http://www.sitepoint.com/how-to-code-html-email-newsletters/

`multipart/alternative` is a container for equal `text/html` eg. HTML and `text/plain` eg. plaintext contents, in this case the e-mail client can choose which one it wants to use. In your case you define only the html content and no plaintext. Plaintext in most cases is not needed anyway, so it should not be an issue.
