### ISSUE TITLE
Cant get past EHLO [127.0.0.1] when forking a Nodemailer Process with Electron

### ISSUE THREAD

**Issue by charlesgiroux** [andris9/Nodemailer#518]
I've been trying setup a child_process in my Electron app that sends an email with nodemailer. I'm using child_process.fork.

When I directly invoke the scripts with node parent.js, my child_process sends the email just fine!

When the child_process is forked within my electron app, I cannot get past EHLO [127.0.0.1]. After this nothing happens even though this._socket.write(new Buffer(str + '\r\n', 'utf-8')); return true (Line 571 of smtp-connection.js.

If I used child_process.spawn, the email is sent correctly...

parents.js:
```
var childProcess = require('child_process');
var childSender = childProcess.fork(path-to-child)

childSender.on('message', function(msg) {
// Do something with msg
});
```
child.js:
```
// I even dumbed down my child.js to your simple example to see if it would change anything, but I still get nothing from child_process.fork :(

var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
    service: 'Gmail',
    auth: {
        user: 'xxxxxxxxx@gmail.com',
        pass: 'xxxxxxxxxxxxx'
    }
});



// setup e-mail data with unicode symbols
var mailOptions = {
    from: 'xxxxxx@gmail.com', // sender address
    to: 'xxxxxx@gmail.com', // list of receivers
    subject: 'Hello', // Subject line
    text: 'Hello world', // plaintext body
    html: '<b>Hello world</b>' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return process.send(error);
    }
    process.send('Message sent: ' + info.response);

});
```

Any ideas?

**Comment by andris9** [comment]
No idea, Electron is not officially supported. If you find the answer though, maybe update the ticket so others would understand it as well
