### ISSUE TITLE
Error: connect EACCES

### ISSUE THREAD

**Issue by DuhSokola** [andris9/Nodemailer#519]
Does someone know why it fails? Need Help, pls
Server doesnt have authorisation.

var transporter = nodemailer.createTransport(smtpTransport({
            host: 'smtp.****.***.web',
            port: '25'
        }));

{ [Error: connect EACCES ***.**.**.***:25]
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'connect',
  address: ' ***.**.**.***',
  port: 25 }

**Comment by andris9** [comment]
It means your firewall blocked outgoing connection to port 25. Check if your smtp provider allows to use other ports as well (465, 587, 2525 etc.)
