### ISSUE TITLE
when `nodemailer.createTransport()` has no parameter, sometimes `Error: Sending failed`

### ISSUE THREAD

**Issue by DIMPLY** [andris9/Nodemailer#524]
```javascript
var nodemailer = require('nodemailer');

// create reusable transporter object
var transporter = nodemailer.createTransport();

var send = function send(content,title,from){
    // setup e-mail data with unicode symbols
    var mailOptions = {
        from: from, // sender address
        to: 'dimply@126.com', // list of receivers
        subject: 'USER FEEDBACK: '+title, // Subject line
        text: content, // plaintext body
        html: '<b>'+content+'</b>' // html body
    };
    console.log(mailOptions);

    var promise = new Promise(function(resolve,reject){
        // send mail with defined transport object
        transporter.sendMail(mailOptions, function(error, info){
            if(error){
                console.log('error: '+error);
                reject(error);
            }
            else{
                console.log('info: ',info);
                resolve(info);
            }
        });
    });

    return promise;
}

module.exports = send;
```

**Comment by DIMPLY** [comment]
I tested successfully with `send('anything','anything','a@a.a')`, `send('anything','anything','d@a.a')`, `send('anything','anything','ign@d.com')`, but failed with `send('anything','anything','d@126.com')`, `send('anything','anything','d@gmail.com')`, `send('anything','anything','a@qq.com')`, all with the same error message: `Error: sending failed`

**Comment by Vietworm** [comment]
Hi @DIMPLY , your code looks good already. I need you make sure define service, authentication your account for createTransport().

**Comment by andris9** [comment]
When you do not provide a configuration, Nodemailer defaults to sending messages directly to recipients MX with [nodemailer-direct-transport](https://github.com/andris9/nodemailer-direct-transport). If your host is not "trusted" by recipient MX servers (eg. you are trying to send messages from a dynamically allocated IP address or your VPS is brand new and no-one has never seen this IP address before or your IP address used to belong to a spammer etc.) then your message is rejected. If you do not control who the recipients are, then using direct sending is not advised.
