### ISSUE TITLE
not able to login when using custom email

### ISSUE THREAD

**Issue by blikenoother** [andris9/Nodemailer#526]
I am using custom email which is hosted with google app (user.name@nongmail.com) (similar UI as gmail user)

Following is error:

{ [Error: Invalid login]
  code: 'EAUTH',
  response: '534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbuPD\n534-5.7.14 bUsXeNFLrKR-axMYXZ8J4I00tcowyetMQ9E3_uuQDDLFKoShL0by4FfOXcF_ESih3jmAJS\n534-5.7.14 276RFvUdHm_SnkdCrkYO0luUboyvAX9Knr-ApxQznmWf3PN0coJbNM_eP_og1mzlC-kbJW\n534-5.7.14 bC3pf4APrUdt-GSvUo-BLuaVq278ByJvHiGn51QZ9P5CilA4ucYi76DMrGQwSN0ClMtIz2\n534-5.7.14 Rjis7C8YLx6jPnptDiAqMdNehs7A> Please log in via your web browser and\n534-5.7.14 then try again.\n534-5.7.14  Learn more at\n534 5.7.14  https://support.google.com/mail/answer/78754 f5sm20459466pas.8 - gsmtp',
  responseCode: 534 }

**Comment by andris9** [comment]
You may need to ["Allow Less Secure Apps"](https://www.google.com/settings/security/lesssecureapps) in your gmail account (it's all the way at the bottom). You also may need to ["Allow access to your Google account"](https://accounts.google.com/DisplayUnlockCaptcha). See also notes about using Gmail [here](https://github.com/andris9/Nodemailer/blob/master/README.md#using-gmail)
