### ISSUE TITLE
How to send via SMTP and STARTTLS ?

### ISSUE THREAD

**Issue by Ulawun** [andris9/Nodemailer#527]
Hello Andris,

I'm using this transporter:

var transporter = nodemailer.createTransport( smtpTransport(
{	host: "smtp.domain.com",
	port: 587, // STARTTLS
	auth:
	{	user: user,
		pass: '???',
	},
} ));

Sometimes it's working, mostly I get this error:
Error: Hostname/IP doesn't match certificate's altnames

Any idea, please ?
The same SMTP account runs perfect with Thunderbird.
Was is Thunderbird doing different, than your package ?
Thunderbird is using port: 587 and STARTTLS.

Thanks in advance

**Comment by andris9** [comment]
You do not need to specify anything for STARTTLS use as Nodemailer upgrades to STARTTLS if STARTTLS is available. If you are useing a self-signed certificate, then you can override the strict check with `tls.rejectUnauthorized`:

```
{
    host: 'smtp.domain.com',
    ...
    tls:{
         rejectUnauthorized: false
    }
}
```

**Comment by Ulawun** [comment]
Andris,
1000 thanks.
It's working great.
Best wishes.
