### ISSUE TITLE
BCC recipients limited to 100?

### ISSUE THREAD

**Issue by jorgeazevedo** [andris9/Nodemailer#528]
Hi,

I'm trying to get nodemailer to send an e-mail to hundreds of people using my Goggle Apps corporate gmail account. Everything works, except that it only uses the first 100 emails from my bcc string that had around 1000 of them. I ended up sending them 100 at a time.

Can someone help me understand why this is happening? I've added `maxMessages: Infinity` to the transporter configuration, but it didn't change the behaviour. I'm on node 0.12. 

```javascript
var user = "mail@gmail.com"
var pass = "xxxxxxxxxxxx";
var bcc = "mail1@gmail.com, mail2@gmail.com" /* comma separated list of 1000 emails */

var transporter = nodemailer.createTransport({
    service: 'Gmail',
    maxMessages: Infinity,
    auth: {
        user: user,
        pass: pass
    }
});

var mailOptions = {
    from: user,
    bcc: bcc,
    subject: 'Email subject',
    html: fs.readFileSync('./email.html', 'utf8')
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
/* etc */
});
```

**Comment by andris9** [comment]
This is a Gmail enforced hard limit and not related to Nodemailer. See all Gmail limits [here](https://support.google.com/a/answer/166852?hl=en).

**Comment by jorgeazevedo** [comment]
@andris9 Thanks so much for the quick reply! I think we have an SMTP relay available, so I might switch to using that instead. Many thanks!
