### ISSUE TITLE
CERT_HAS_EXPIRED Error: certificate has expired

### ISSUE THREAD

**Issue by Nedudi** [andris9/Nodemailer#530]
Started to get error using nodemailer and mandrill smtp. 

     Erorr: { [Error: certificate has expired] code: 'CERT_HAS_EXPIRED' }

Could you please describe, what can be the reason

It happens hour ago with different servers on different domains/ip to me
maybe problems on Mandrill's side
but I am not sure

thanks for any help in advance

**Comment by Nedudi** [comment]
Changing mandlill's api key does not help

**Comment by laxrph10** [comment]
+1 Experiencing this issue as well.

**Comment by Nedudi** [comment]
http://status.mandrillapp.com/

## this was a problem on mandrill side

 Expired Certificate Errors
A roll out of new certificates last week has caused some users to experience problems sending mail—this was due to the expiration of the old certificate and an issue in our configuration. The users effected were sending through SMTP with STARTTLS. HTTPS API calls were not affected. We are currently working on a fix and will update when resolved. 
12:21 PM UTC The configuration error was corrected at 12:05 UTC. SMTP with STARTTLS is now working correctly in all regions.
December 18, 2015 12:04 PM UTC

**Comment by ruler88** [comment]
This happened again Jan 28, 2016 11:25AM PST

**Comment by arvindgt** [comment]
Apply below in your transporter setting - 

tls: {rejectUnauthorized: false},

For Example :

var transporter = nodemailer.createTransport({
host: 'smtp.example.com',
port: 587,
auth: {
    user: 'username',
    pass: 'userpassword'
},
tls: {rejectUnauthorized: false} 
});
