### ISSUE TITLE
base64 images in outlook

### ISSUE THREAD

**Issue by smolleyes** [andris9/Nodemailer#532]
hi

do i have something special to get outllook display base 64 images i can see them in all mail clients i tried BUT outllook ... (damn windows..) 

tried outlook 2010 and 2016, same problem

thanks !

**Comment by andris9** [comment]
By base64 images do you mean images in data URIs? This is not related to Nodemailer, as HTML content is not processed by Nodemailer, whatever you pass to it is delivered to destination as is. If data URIs do not work, use attachments as embedded images [described here](https://github.com/andris9/Nodemailer#using-embedded-images)

**Comment by niftylettuce** [comment]
Try this package: https://github.com/crocodilejs/nodemailer-base64-to-s3
