### ISSUE TITLE
How can I send a email with internal email service?

### ISSUE THREAD

**Issue by hellfiresong** [andris9/Nodemailer#534]
I am trapped with a problem. How can I send a email with internal email service? for example: xxx.alibaba-inc.com(this is an enterprise email address). Current situation is in NodeJS environment. I try to use nodemailer library which can support most cloud mail service, but can't support our own internal email. If someone who had solved this problem, please give me some advice. Server side always return error message: connect ECONNREFUSED

**Comment by andris9** [comment]
Most e-mail servers support SMTP based sending. If you know the SMTP server details for your internal e-mail service then you can send mail like this:

```javascript
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    host: 'smtp.server.hostname',
    port: 465,
    secure: true, // if port is 587 or 25, then secure is usually false
    auth: {
        user: 'smtp username',
        pass: 'smtp password'
    }
});
transporter.sendMail({
    from: 'sender@example.com',
    to: 'receiver@example.com',
    subject: 'hello world!',
    text: 'message text'
});
```
