### ISSUE TITLE
[Error: Greeting never received] code: 'ETIMEDOUT' 

### ISSUE THREAD

**Issue by wangning0** [andris9/Nodemailer#535]
when I use this module ,find the problem.please help me ,thank u.
code:

var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
      host: "smtp.qq.com", // 主机
      secureConnection: true, // use SSL
      port: 465, // port SMTP 
      auth: {
        user: "xxxxxxx@qq.com", 
        pass: "xxxxxx"
      }
});

var mailOptions = {
    from: 'xxxxxx', // sender address
    to: 'xxxxx', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world ✔', // plaintext body
    html: '<b>Hello world ✔</b>' // html body
};

transporter.sendMail(mailOptions, function(error, info){
    if(error){
        console.log(error);
    }else{
        console.log('Message sent: ' + info.response);
    }
});

**Comment by andris9** [comment]
Use *secure* instead of *secureConnection*
